# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arpseq.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from midi import *
from mopho import *
import math

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ArpDialog(object):
	def setupUi(self, Dialog):
		Dialog.setObjectName(_fromUtf8("Dialog"))
		Dialog.resize(400, 300)
		self.arpTempo = QtGui.QSpinBox(Dialog)
		self.arpTempo.setGeometry(QtCore.QRect(20, 30, 42, 22))
		self.arpTempo.setObjectName(_fromUtf8("arpTempo"))
		self.arpTempo.valueChanged.connect(self.ArpTempo)
		self.arpTempo.setMinimum(30)
		self.arpTempo.setMaximum(250)
		
		self.label = QtGui.QLabel(Dialog)
		self.label.setGeometry(QtCore.QRect(20, 10, 46, 13))
		self.label.setObjectName(_fromUtf8("label"))
		self.arpClock = QtGui.QComboBox(Dialog)
		self.arpClock.setGeometry(QtCore.QRect(80, 30, 69, 22))
		self.arpClock.setObjectName(_fromUtf8("arpClock"))
		self.arpClock.addItem(_fromUtf8(""))
		self.arpClock.addItem(_fromUtf8(""))
		self.arpClock.addItem(_fromUtf8(""))
		self.arpClock.addItem(_fromUtf8(""))
		self.arpClock.addItem(_fromUtf8(""))
		self.arpClock.addItem(_fromUtf8(""))
		self.arpClock.addItem(_fromUtf8(""))
		self.arpClock.addItem(_fromUtf8(""))
		self.arpClock.addItem(_fromUtf8(""))
		self.arpClock.addItem(_fromUtf8(""))
		self.arpClock.addItem(_fromUtf8(""))
		self.arpClock.addItem(_fromUtf8(""))
		self.arpClock.addItem(_fromUtf8(""))
		self.arpClock.currentIndexChanged.connect(self.ArpClock)

		self.label_2 = QtGui.QLabel(Dialog)
		self.label_2.setGeometry(QtCore.QRect(80, 10, 71, 16))
		self.label_2.setObjectName(_fromUtf8("label_2"))
		self.arpMode = QtGui.QComboBox(Dialog)
		self.arpMode.setGeometry(QtCore.QRect(20, 80, 69, 22))
		self.arpMode.setObjectName(_fromUtf8("arpMode"))
		self.arpMode.addItem(_fromUtf8(""))
		self.arpMode.addItem(_fromUtf8(""))
		self.arpMode.addItem(_fromUtf8(""))
		self.arpMode.addItem(_fromUtf8(""))
		self.arpMode.currentIndexChanged.connect(self.ArpMode)

		self.label_3 = QtGui.QLabel(Dialog)
		self.label_3.setGeometry(QtCore.QRect(20, 60, 46, 13))
		self.label_3.setObjectName(_fromUtf8("label_3"))
		self.arpOn = QtGui.QCheckBox(Dialog)
		self.arpOn.setGeometry(QtCore.QRect(110, 80, 70, 17))
		self.arpOn.setObjectName(_fromUtf8("arpOn"))
		self.arpOn.toggled.connect(self.ArpOn)

		self.arpSeqTrig = QtGui.QComboBox(Dialog)
		self.arpSeqTrig.setGeometry(QtCore.QRect(20, 130, 69, 22))
		self.arpSeqTrig.setObjectName(_fromUtf8("arpSeqTrig"))
		self.arpSeqTrig.addItem(_fromUtf8(""))
		self.arpSeqTrig.addItem(_fromUtf8(""))
		self.arpSeqTrig.addItem(_fromUtf8(""))
		self.arpSeqTrig.addItem(_fromUtf8(""))
		self.arpSeqTrig.addItem(_fromUtf8(""))
		self.arpSeqTrig.addItem(_fromUtf8(""))
		self.arpSeqTrig.currentIndexChanged.connect(self.ArpSeqTrig)

		self.label_4 = QtGui.QLabel(Dialog)
		self.label_4.setGeometry(QtCore.QRect(20, 110, 101, 16))
		self.label_4.setObjectName(_fromUtf8("label_4"))
		self.arpGatedSeq = QtGui.QCheckBox(Dialog)
		self.arpGatedSeq.setGeometry(QtCore.QRect(110, 130, 70, 17))
		self.arpGatedSeq.setObjectName(_fromUtf8("arpGatedSeq"))
		self.arpGatedSeq.toggled.connect(self.ArpGatedSeq)

		self.arpSeq3Dest = QtGui.QComboBox(Dialog)
		self.arpSeq3Dest.setGeometry(QtCore.QRect(220, 150, 121, 22))
		self.arpSeq3Dest.setObjectName(_fromUtf8("arpSeq3Dest"))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.addItem(_fromUtf8(""))
		self.arpSeq3Dest.setItemText(48, _fromUtf8(""))
		self.arpSeq3Dest.currentIndexChanged.connect(self.ArpSeq3Dest)

		self.label_5 = QtGui.QLabel(Dialog)
		self.label_5.setGeometry(QtCore.QRect(220, 30, 61, 16))
		self.label_5.setObjectName(_fromUtf8("label_5"))
		self.label_9 = QtGui.QLabel(Dialog)
		self.label_9.setGeometry(QtCore.QRect(220, 180, 61, 16))
		self.label_9.setObjectName(_fromUtf8("label_9"))
		self.arpSeq4Dest = QtGui.QComboBox(Dialog)
		self.arpSeq4Dest.setGeometry(QtCore.QRect(220, 200, 121, 22))
		self.arpSeq4Dest.setObjectName(_fromUtf8("arpSeq4Dest"))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.addItem(_fromUtf8(""))
		self.arpSeq4Dest.setItemText(48, _fromUtf8(""))
		self.arpSeq4Dest.currentIndexChanged.connect(self.ArpSeq4Dest)

		self.arpSeq2Dest = QtGui.QComboBox(Dialog)
		self.arpSeq2Dest.setGeometry(QtCore.QRect(220, 100, 121, 22))
		self.arpSeq2Dest.setObjectName(_fromUtf8("arpSeq2Dest"))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.addItem(_fromUtf8(""))
		self.arpSeq2Dest.setItemText(48, _fromUtf8(""))
		self.arpSeq2Dest.currentIndexChanged.connect(self.ArpSeq2Dest)

		self.label_7 = QtGui.QLabel(Dialog)
		self.label_7.setGeometry(QtCore.QRect(220, 80, 71, 16))
		self.label_7.setObjectName(_fromUtf8("label_7"))
		self.arpSeq1Dest = QtGui.QComboBox(Dialog)
		self.arpSeq1Dest.setGeometry(QtCore.QRect(220, 50, 121, 22))
		self.arpSeq1Dest.setObjectName(_fromUtf8("arpSeq1Dest"))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.addItem(_fromUtf8(""))
		self.arpSeq1Dest.setItemText(48, _fromUtf8(""))
		self.arpSeq1Dest.currentIndexChanged.connect(self.ArpSeq1Dest)

		self.label_8 = QtGui.QLabel(Dialog)
		self.label_8.setGeometry(QtCore.QRect(220, 130, 61, 16))
		self.label_8.setObjectName(_fromUtf8("label_8"))

		self.retranslateUi(Dialog)
		QtCore.QMetaObject.connectSlotsByName(Dialog)

	def retranslateUi(self, Dialog):
		Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
		self.label.setText(_translate("Dialog", "Tempo", None))
		self.arpClock.setItemText(0, _translate("Dialog", "Half Note", None))
		self.arpClock.setItemText(1, _translate("Dialog", "Quarter", None))
		self.arpClock.setItemText(2, _translate("Dialog", "Eigth", None))
		self.arpClock.setItemText(3, _translate("Dialog", "Eigth Half swing", None))
		self.arpClock.setItemText(4, _translate("Dialog", "Eigth Full swing", None))
		self.arpClock.setItemText(5, _translate("Dialog", "Eigth Triplets", None))
		self.arpClock.setItemText(6, _translate("Dialog", "Sixteenth", None))
		self.arpClock.setItemText(7, _translate("Dialog", "Sixteenth Half swing", None))
		self.arpClock.setItemText(8, _translate("Dialog", "Sixteenth full swing", None))
		self.arpClock.setItemText(9, _translate("Dialog", "Sixteen Trplets", None))
		self.arpClock.setItemText(10, _translate("Dialog", "Thirty Second", None))
		self.arpClock.setItemText(11, _translate("Dialog", "Thirty-Second triplets", None))
		self.arpClock.setItemText(12, _translate("Dialog", "Sixty-Fourth Triplets", None))
		self.label_2.setText(_translate("Dialog", "Clock Divide", None))
		self.arpMode.setItemText(0, _translate("Dialog", "Up", None))
		self.arpMode.setItemText(1, _translate("Dialog", "Down", None))
		self.arpMode.setItemText(2, _translate("Dialog", "Up/Down", None))
		self.arpMode.setItemText(3, _translate("Dialog", "Assign", None))
		self.label_3.setText(_translate("Dialog", "Arp Mode", None))
		self.arpOn.setText(_translate("Dialog", "Arp On", None))
		self.arpSeqTrig.setItemText(0, _translate("Dialog", "Normal", None))
		self.arpSeqTrig.setItemText(1, _translate("Dialog", "Normal, no reset", None))
		self.arpSeqTrig.setItemText(2, _translate("Dialog", "No Gate", None))
		self.arpSeqTrig.setItemText(3, _translate("Dialog", "No gate/no reset", None))
		self.arpSeqTrig.setItemText(4, _translate("Dialog", "Key Step", None))
		self.arpSeqTrig.setItemText(5, _translate("Dialog", "Audio In", None))
		self.label_4.setText(_translate("Dialog", "Sequencer Trigger", None))
		self.arpGatedSeq.setText(_translate("Dialog", "Gated Seq", None))
		self.arpSeq3Dest.setItemText(0, _translate("Dialog", "Off", None))
		self.arpSeq3Dest.setItemText(1, _translate("Dialog", "Osc 1 Freq", None))
		self.arpSeq3Dest.setItemText(2, _translate("Dialog", "Osc 2 Freq", None))
		self.arpSeq3Dest.setItemText(3, _translate("Dialog", "Osc 1+2 Freq", None))
		self.arpSeq3Dest.setItemText(4, _translate("Dialog", "Osc Mix", None))
		self.arpSeq3Dest.setItemText(5, _translate("Dialog", "Noise Level", None))
		self.arpSeq3Dest.setItemText(6, _translate("Dialog", "Osc 1 PW", None))
		self.arpSeq3Dest.setItemText(7, _translate("Dialog", "Osc 2 PW", None))
		self.arpSeq3Dest.setItemText(8, _translate("Dialog", "Osc 1+2 PW", None))
		self.arpSeq3Dest.setItemText(9, _translate("Dialog", "Filter Freq", None))
		self.arpSeq3Dest.setItemText(10, _translate("Dialog", "Resonance", None))
		self.arpSeq3Dest.setItemText(11, _translate("Dialog", "Filter Audio Mod", None))
		self.arpSeq3Dest.setItemText(12, _translate("Dialog", "VCA Level", None))
		self.arpSeq3Dest.setItemText(13, _translate("Dialog", "Pan", None))
		self.arpSeq3Dest.setItemText(14, _translate("Dialog", "LFO 1 Freq", None))
		self.arpSeq3Dest.setItemText(15, _translate("Dialog", "LFO2 Freq", None))
		self.arpSeq3Dest.setItemText(16, _translate("Dialog", "LFO3 Freq", None))
		self.arpSeq3Dest.setItemText(17, _translate("Dialog", "LFO4 Freq", None))
		self.arpSeq3Dest.setItemText(18, _translate("Dialog", "All LFO Freq", None))
		self.arpSeq3Dest.setItemText(19, _translate("Dialog", "LFO1 Amt", None))
		self.arpSeq3Dest.setItemText(20, _translate("Dialog", "LFO2 Amt", None))
		self.arpSeq3Dest.setItemText(21, _translate("Dialog", "LFO3 Amt", None))
		self.arpSeq3Dest.setItemText(22, _translate("Dialog", "LFO4 Amt", None))
		self.arpSeq3Dest.setItemText(23, _translate("Dialog", "All LFO Amt", None))
		self.arpSeq3Dest.setItemText(24, _translate("Dialog", "Filter Env Amt", None))
		self.arpSeq3Dest.setItemText(25, _translate("Dialog", "Amp Env Amt", None))
		self.arpSeq3Dest.setItemText(26, _translate("Dialog", "Env 3 Amt", None))
		self.arpSeq3Dest.setItemText(27, _translate("Dialog", "All Env Amt", None))
		self.arpSeq3Dest.setItemText(28, _translate("Dialog", "Env1 Attak", None))
		self.arpSeq3Dest.setItemText(29, _translate("Dialog", "Env2 Attack", None))
		self.arpSeq3Dest.setItemText(30, _translate("Dialog", "Env3 Attack", None))
		self.arpSeq3Dest.setItemText(31, _translate("Dialog", "All Env Attacks", None))
		self.arpSeq3Dest.setItemText(32, _translate("Dialog", "Env1 Decay", None))
		self.arpSeq3Dest.setItemText(33, _translate("Dialog", "Env2 Decay", None))
		self.arpSeq3Dest.setItemText(34, _translate("Dialog", "Env3 Decay", None))
		self.arpSeq3Dest.setItemText(35, _translate("Dialog", "All Env Decays", None))
		self.arpSeq3Dest.setItemText(36, _translate("Dialog", "Env1 Release", None))
		self.arpSeq3Dest.setItemText(37, _translate("Dialog", "Env2 Release", None))
		self.arpSeq3Dest.setItemText(38, _translate("Dialog", "Env3 Release", None))
		self.arpSeq3Dest.setItemText(39, _translate("Dialog", "All Env Releases", None))
		self.arpSeq3Dest.setItemText(40, _translate("Dialog", "Mod1 Amt", None))
		self.arpSeq3Dest.setItemText(41, _translate("Dialog", "Mod2 Amt", None))
		self.arpSeq3Dest.setItemText(42, _translate("Dialog", "Mod3 Amt", None))
		self.arpSeq3Dest.setItemText(43, _translate("Dialog", "Mod4 Amt", None))
		self.arpSeq3Dest.setItemText(44, _translate("Dialog", "Ext Audio In Level", None))
		self.arpSeq3Dest.setItemText(45, _translate("Dialog", "Sub Osc1", None))
		self.arpSeq3Dest.setItemText(46, _translate("Dialog", "Sub Osc 2", None))
		self.arpSeq3Dest.setItemText(47, _translate("Dialog", "Skew 1/2", None))
		self.label_5.setText(_translate("Dialog", "Seq1 Dest", None))
		self.label_9.setText(_translate("Dialog", "Seq4 Dest", None))
		self.arpSeq4Dest.setItemText(0, _translate("Dialog", "Off", None))
		self.arpSeq4Dest.setItemText(1, _translate("Dialog", "Osc 1 Freq", None))
		self.arpSeq4Dest.setItemText(2, _translate("Dialog", "Osc 2 Freq", None))
		self.arpSeq4Dest.setItemText(3, _translate("Dialog", "Osc 1+2 Freq", None))
		self.arpSeq4Dest.setItemText(4, _translate("Dialog", "Osc Mix", None))
		self.arpSeq4Dest.setItemText(5, _translate("Dialog", "Noise Level", None))
		self.arpSeq4Dest.setItemText(6, _translate("Dialog", "Osc 1 PW", None))
		self.arpSeq4Dest.setItemText(7, _translate("Dialog", "Osc 2 PW", None))
		self.arpSeq4Dest.setItemText(8, _translate("Dialog", "Osc 1+2 PW", None))
		self.arpSeq4Dest.setItemText(9, _translate("Dialog", "Filter Freq", None))
		self.arpSeq4Dest.setItemText(10, _translate("Dialog", "Resonance", None))
		self.arpSeq4Dest.setItemText(11, _translate("Dialog", "Filter Audio Mod", None))
		self.arpSeq4Dest.setItemText(12, _translate("Dialog", "VCA Level", None))
		self.arpSeq4Dest.setItemText(13, _translate("Dialog", "Pan", None))
		self.arpSeq4Dest.setItemText(14, _translate("Dialog", "LFO 1 Freq", None))
		self.arpSeq4Dest.setItemText(15, _translate("Dialog", "LFO2 Freq", None))
		self.arpSeq4Dest.setItemText(16, _translate("Dialog", "LFO3 Freq", None))
		self.arpSeq4Dest.setItemText(17, _translate("Dialog", "LFO4 Freq", None))
		self.arpSeq4Dest.setItemText(18, _translate("Dialog", "All LFO Freq", None))
		self.arpSeq4Dest.setItemText(19, _translate("Dialog", "LFO1 Amt", None))
		self.arpSeq4Dest.setItemText(20, _translate("Dialog", "LFO2 Amt", None))
		self.arpSeq4Dest.setItemText(21, _translate("Dialog", "LFO3 Amt", None))
		self.arpSeq4Dest.setItemText(22, _translate("Dialog", "LFO4 Amt", None))
		self.arpSeq4Dest.setItemText(23, _translate("Dialog", "All LFO Amt", None))
		self.arpSeq4Dest.setItemText(24, _translate("Dialog", "Filter Env Amt", None))
		self.arpSeq4Dest.setItemText(25, _translate("Dialog", "Amp Env Amt", None))
		self.arpSeq4Dest.setItemText(26, _translate("Dialog", "Env 3 Amt", None))
		self.arpSeq4Dest.setItemText(27, _translate("Dialog", "All Env Amt", None))
		self.arpSeq4Dest.setItemText(28, _translate("Dialog", "Env1 Attak", None))
		self.arpSeq4Dest.setItemText(29, _translate("Dialog", "Env2 Attack", None))
		self.arpSeq4Dest.setItemText(30, _translate("Dialog", "Env3 Attack", None))
		self.arpSeq4Dest.setItemText(31, _translate("Dialog", "All Env Attacks", None))
		self.arpSeq4Dest.setItemText(32, _translate("Dialog", "Env1 Decay", None))
		self.arpSeq4Dest.setItemText(33, _translate("Dialog", "Env2 Decay", None))
		self.arpSeq4Dest.setItemText(34, _translate("Dialog", "Env3 Decay", None))
		self.arpSeq4Dest.setItemText(35, _translate("Dialog", "All Env Decays", None))
		self.arpSeq4Dest.setItemText(36, _translate("Dialog", "Env1 Release", None))
		self.arpSeq4Dest.setItemText(37, _translate("Dialog", "Env2 Release", None))
		self.arpSeq4Dest.setItemText(38, _translate("Dialog", "Env3 Release", None))
		self.arpSeq4Dest.setItemText(39, _translate("Dialog", "All Env Releases", None))
		self.arpSeq4Dest.setItemText(40, _translate("Dialog", "Mod1 Amt", None))
		self.arpSeq4Dest.setItemText(41, _translate("Dialog", "Mod2 Amt", None))
		self.arpSeq4Dest.setItemText(42, _translate("Dialog", "Mod3 Amt", None))
		self.arpSeq4Dest.setItemText(43, _translate("Dialog", "Mod4 Amt", None))
		self.arpSeq4Dest.setItemText(44, _translate("Dialog", "Ext Audio In Level", None))
		self.arpSeq4Dest.setItemText(45, _translate("Dialog", "Sub Osc1", None))
		self.arpSeq4Dest.setItemText(46, _translate("Dialog", "Sub Osc 2", None))
		self.arpSeq4Dest.setItemText(47, _translate("Dialog", "Skew 1/2", None))
		self.arpSeq2Dest.setItemText(0, _translate("Dialog", "Off", None))
		self.arpSeq2Dest.setItemText(1, _translate("Dialog", "Osc 1 Freq", None))
		self.arpSeq2Dest.setItemText(2, _translate("Dialog", "Osc 2 Freq", None))
		self.arpSeq2Dest.setItemText(3, _translate("Dialog", "Osc 1+2 Freq", None))
		self.arpSeq2Dest.setItemText(4, _translate("Dialog", "Osc Mix", None))
		self.arpSeq2Dest.setItemText(5, _translate("Dialog", "Noise Level", None))
		self.arpSeq2Dest.setItemText(6, _translate("Dialog", "Osc 1 PW", None))
		self.arpSeq2Dest.setItemText(7, _translate("Dialog", "Osc 2 PW", None))
		self.arpSeq2Dest.setItemText(8, _translate("Dialog", "Osc 1+2 PW", None))
		self.arpSeq2Dest.setItemText(9, _translate("Dialog", "Filter Freq", None))
		self.arpSeq2Dest.setItemText(10, _translate("Dialog", "Resonance", None))
		self.arpSeq2Dest.setItemText(11, _translate("Dialog", "Filter Audio Mod", None))
		self.arpSeq2Dest.setItemText(12, _translate("Dialog", "VCA Level", None))
		self.arpSeq2Dest.setItemText(13, _translate("Dialog", "Pan", None))
		self.arpSeq2Dest.setItemText(14, _translate("Dialog", "LFO 1 Freq", None))
		self.arpSeq2Dest.setItemText(15, _translate("Dialog", "LFO2 Freq", None))
		self.arpSeq2Dest.setItemText(16, _translate("Dialog", "LFO3 Freq", None))
		self.arpSeq2Dest.setItemText(17, _translate("Dialog", "LFO4 Freq", None))
		self.arpSeq2Dest.setItemText(18, _translate("Dialog", "All LFO Freq", None))
		self.arpSeq2Dest.setItemText(19, _translate("Dialog", "LFO1 Amt", None))
		self.arpSeq2Dest.setItemText(20, _translate("Dialog", "LFO2 Amt", None))
		self.arpSeq2Dest.setItemText(21, _translate("Dialog", "LFO3 Amt", None))
		self.arpSeq2Dest.setItemText(22, _translate("Dialog", "LFO4 Amt", None))
		self.arpSeq2Dest.setItemText(23, _translate("Dialog", "All LFO Amt", None))
		self.arpSeq2Dest.setItemText(24, _translate("Dialog", "Filter Env Amt", None))
		self.arpSeq2Dest.setItemText(25, _translate("Dialog", "Amp Env Amt", None))
		self.arpSeq2Dest.setItemText(26, _translate("Dialog", "Env 3 Amt", None))
		self.arpSeq2Dest.setItemText(27, _translate("Dialog", "All Env Amt", None))
		self.arpSeq2Dest.setItemText(28, _translate("Dialog", "Env1 Attak", None))
		self.arpSeq2Dest.setItemText(29, _translate("Dialog", "Env2 Attack", None))
		self.arpSeq2Dest.setItemText(30, _translate("Dialog", "Env3 Attack", None))
		self.arpSeq2Dest.setItemText(31, _translate("Dialog", "All Env Attacks", None))
		self.arpSeq2Dest.setItemText(32, _translate("Dialog", "Env1 Decay", None))
		self.arpSeq2Dest.setItemText(33, _translate("Dialog", "Env2 Decay", None))
		self.arpSeq2Dest.setItemText(34, _translate("Dialog", "Env3 Decay", None))
		self.arpSeq2Dest.setItemText(35, _translate("Dialog", "All Env Decays", None))
		self.arpSeq2Dest.setItemText(36, _translate("Dialog", "Env1 Release", None))
		self.arpSeq2Dest.setItemText(37, _translate("Dialog", "Env2 Release", None))
		self.arpSeq2Dest.setItemText(38, _translate("Dialog", "Env3 Release", None))
		self.arpSeq2Dest.setItemText(39, _translate("Dialog", "All Env Releases", None))
		self.arpSeq2Dest.setItemText(40, _translate("Dialog", "Mod1 Amt", None))
		self.arpSeq2Dest.setItemText(41, _translate("Dialog", "Mod2 Amt", None))
		self.arpSeq2Dest.setItemText(42, _translate("Dialog", "Mod3 Amt", None))
		self.arpSeq2Dest.setItemText(43, _translate("Dialog", "Mod4 Amt", None))
		self.arpSeq2Dest.setItemText(44, _translate("Dialog", "Ext Audio In Level", None))
		self.arpSeq2Dest.setItemText(45, _translate("Dialog", "Sub Osc1", None))
		self.arpSeq2Dest.setItemText(46, _translate("Dialog", "Sub Osc 2", None))
		self.arpSeq2Dest.setItemText(47, _translate("Dialog", "Skew 1/2", None))
		self.label_7.setText(_translate("Dialog", "Seq2 Dest", None))
		self.arpSeq1Dest.setItemText(0, _translate("Dialog", "Off", None))
		self.arpSeq1Dest.setItemText(1, _translate("Dialog", "Osc 1 Freq", None))
		self.arpSeq1Dest.setItemText(2, _translate("Dialog", "Osc 2 Freq", None))
		self.arpSeq1Dest.setItemText(3, _translate("Dialog", "Osc 1+2 Freq", None))
		self.arpSeq1Dest.setItemText(4, _translate("Dialog", "Osc Mix", None))
		self.arpSeq1Dest.setItemText(5, _translate("Dialog", "Noise Level", None))
		self.arpSeq1Dest.setItemText(6, _translate("Dialog", "Osc 1 PW", None))
		self.arpSeq1Dest.setItemText(7, _translate("Dialog", "Osc 2 PW", None))
		self.arpSeq1Dest.setItemText(8, _translate("Dialog", "Osc 1+2 PW", None))
		self.arpSeq1Dest.setItemText(9, _translate("Dialog", "Filter Freq", None))
		self.arpSeq1Dest.setItemText(10, _translate("Dialog", "Resonance", None))
		self.arpSeq1Dest.setItemText(11, _translate("Dialog", "Filter Audio Mod", None))
		self.arpSeq1Dest.setItemText(12, _translate("Dialog", "VCA Level", None))
		self.arpSeq1Dest.setItemText(13, _translate("Dialog", "Pan", None))
		self.arpSeq1Dest.setItemText(14, _translate("Dialog", "LFO 1 Freq", None))
		self.arpSeq1Dest.setItemText(15, _translate("Dialog", "LFO2 Freq", None))
		self.arpSeq1Dest.setItemText(16, _translate("Dialog", "LFO3 Freq", None))
		self.arpSeq1Dest.setItemText(17, _translate("Dialog", "LFO4 Freq", None))
		self.arpSeq1Dest.setItemText(18, _translate("Dialog", "All LFO Freq", None))
		self.arpSeq1Dest.setItemText(19, _translate("Dialog", "LFO1 Amt", None))
		self.arpSeq1Dest.setItemText(20, _translate("Dialog", "LFO2 Amt", None))
		self.arpSeq1Dest.setItemText(21, _translate("Dialog", "LFO3 Amt", None))
		self.arpSeq1Dest.setItemText(22, _translate("Dialog", "LFO4 Amt", None))
		self.arpSeq1Dest.setItemText(23, _translate("Dialog", "All LFO Amt", None))
		self.arpSeq1Dest.setItemText(24, _translate("Dialog", "Filter Env Amt", None))
		self.arpSeq1Dest.setItemText(25, _translate("Dialog", "Amp Env Amt", None))
		self.arpSeq1Dest.setItemText(26, _translate("Dialog", "Env 3 Amt", None))
		self.arpSeq1Dest.setItemText(27, _translate("Dialog", "All Env Amt", None))
		self.arpSeq1Dest.setItemText(28, _translate("Dialog", "Env1 Attak", None))
		self.arpSeq1Dest.setItemText(29, _translate("Dialog", "Env2 Attack", None))
		self.arpSeq1Dest.setItemText(30, _translate("Dialog", "Env3 Attack", None))
		self.arpSeq1Dest.setItemText(31, _translate("Dialog", "All Env Attacks", None))
		self.arpSeq1Dest.setItemText(32, _translate("Dialog", "Env1 Decay", None))
		self.arpSeq1Dest.setItemText(33, _translate("Dialog", "Env2 Decay", None))
		self.arpSeq1Dest.setItemText(34, _translate("Dialog", "Env3 Decay", None))
		self.arpSeq1Dest.setItemText(35, _translate("Dialog", "All Env Decays", None))
		self.arpSeq1Dest.setItemText(36, _translate("Dialog", "Env1 Release", None))
		self.arpSeq1Dest.setItemText(37, _translate("Dialog", "Env2 Release", None))
		self.arpSeq1Dest.setItemText(38, _translate("Dialog", "Env3 Release", None))
		self.arpSeq1Dest.setItemText(39, _translate("Dialog", "All Env Releases", None))
		self.arpSeq1Dest.setItemText(40, _translate("Dialog", "Mod1 Amt", None))
		self.arpSeq1Dest.setItemText(41, _translate("Dialog", "Mod2 Amt", None))
		self.arpSeq1Dest.setItemText(42, _translate("Dialog", "Mod3 Amt", None))
		self.arpSeq1Dest.setItemText(43, _translate("Dialog", "Mod4 Amt", None))
		self.arpSeq1Dest.setItemText(44, _translate("Dialog", "Ext Audio In Level", None))
		self.arpSeq1Dest.setItemText(45, _translate("Dialog", "Sub Osc1", None))
		self.arpSeq1Dest.setItemText(46, _translate("Dialog", "Sub Osc 2", None))
		self.arpSeq1Dest.setItemText(47, _translate("Dialog", "Skew 1/2", None))
		self.label_8.setText(_translate("Dialog", "Seq3 Dest", None))

	def ArpTempo(self,value):
		x = value
		nrpn = 91
		SendNRPN(nrpn,x,self.midi_channel)
		
	def ArpClock(self,value):
		x = self.arpClock.currentIndex()
		nrpn = 92
		SendNRPN(nrpn,x,self.midi_channel)
		
	def ArpMode(self,value):
		x = self.arpMode.currentIndex()
		nrpn = 97
		SendNRPN(nrpn,x,self.midi_channel)
	
	def ArpSeqTrig(self,value):
		x = self.arpSeqTrig.currentIndex()
		nrpn = 94
		SendNRPN(nrpn,x,self.midi_channel)
			
	def ArpOn(self,value):
		x = self.arpOn.isChecked()
		nrpn = 94
		SendNRPN(nrpn,x,self.midi_channel)
		
	def ArpGatedSeq(self,value):
		x = self.arpGatedSeq.isChecked()
		nrpn = 101
		SendNRPN(nrpn,x,self.midi_channel)
		
	def ArpSeq1Dest(self,value):
		x = self.arpSeq1Dest.currentIndex()
		nrpn = 77
		SendNRPN(nrpn,x,self.midi_channel)
	
	def ArpSeq2Dest(self,value):
		x = self.arpSeq2Dest.currentIndex()
		nrpn = 78
		SendNRPN(nrpn,x,self.midi_channel)
	
	def ArpSeq3Dest(self,value):
		x = self.arpSeq3Dest.currentIndex()
		nrpn = 79
		SendNRPN(nrpn,x,self.midi_channel)
	
	def ArpSeq4Dest(self,value):
		x = self.arpSeq4Dest.currentIndex()
		nrpn = 80
		SendNRPN(nrpn,x,self.midi_channel)
	