from PyQt4 import QtCore, QtGui
from mido.sockets import PortServer,connect
import pickle
import math
import sys

from midi import *
from mopho import *
from patterns import *
from mido import Message,MidiFile,MidiTrack



TEMPO=145.0

PPQ_WHOLE=96
PLAY_LEN=4*PPQ_WHOLE
TX_DELAY=0.01

MIDI_CHANNEL=1
MIDIKB_CHANNEL=1

fib = [0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

MUSIC_SetScaleChord(scale_phrygian_dom,chord_min)

# maximum voice sequencers
MAX_SEQS=16
MAX_TRACKERS=16

def NoteToMopho(n):
	n = n % 12
	o = n / 12
	if(o > 4): o = 4
	
	return o*24+n*2
	
def MophoToNote(n):
	n = n % 24
	o = o / 24
	note = 24+n+o*12

scaling = {}
for i in range(0,125):
	x = scale_minor[i % len(scale_minor)]
	oct = i/12
	n = NoteToMopho(oct*12+x)
	scaling[i] = n
scaling[126] = 126
scaling[127] = 127

note_names = []
for i in range(0,127):
	n = i % 12
	s = name_notes[n]
	x = s + str(i / 12)
	note_names.append(x)

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1029, 737)
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(93, 93, 93);\n"
"color: rgb(255, 255, 255);"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBoxMatrix = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxMatrix.setGeometry(QtCore.QRect(670, 250, 71, 231))
        self.groupBoxMatrix.setObjectName(_fromUtf8("groupBoxMatrix"))
        self.chkMatrix = QtGui.QCheckBox(self.groupBoxMatrix)
        self.chkMatrix.setGeometry(QtCore.QRect(10, 200, 41, 16))
        self.chkMatrix.setObjectName(_fromUtf8("chkMatrix"))
        self.widget = QtGui.QWidget(self.groupBoxMatrix)
        self.widget.setGeometry(QtCore.QRect(10, 20, 51, 180))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.rbMatrix1 = QtGui.QRadioButton(self.widget)
        self.rbMatrix1.setObjectName(_fromUtf8("rbMatrix1"))
        self.verticalLayout.addWidget(self.rbMatrix1)
        self.rbMatrix2 = QtGui.QRadioButton(self.widget)
        self.rbMatrix2.setObjectName(_fromUtf8("rbMatrix2"))
        self.verticalLayout.addWidget(self.rbMatrix2)
        self.rbMatrix3 = QtGui.QRadioButton(self.widget)
        self.rbMatrix3.setObjectName(_fromUtf8("rbMatrix3"))
        self.verticalLayout.addWidget(self.rbMatrix3)
        self.rbMatrix4 = QtGui.QRadioButton(self.widget)
        self.rbMatrix4.setObjectName(_fromUtf8("rbMatrix4"))
        self.verticalLayout.addWidget(self.rbMatrix4)
        self.rbMatrix5 = QtGui.QRadioButton(self.widget)
        self.rbMatrix5.setObjectName(_fromUtf8("rbMatrix5"))
        self.verticalLayout.addWidget(self.rbMatrix5)
        self.rbMatrix6 = QtGui.QRadioButton(self.widget)
        self.rbMatrix6.setObjectName(_fromUtf8("rbMatrix6"))
        self.verticalLayout.addWidget(self.rbMatrix6)
        self.rbMatrix7 = QtGui.QRadioButton(self.widget)
        self.rbMatrix7.setObjectName(_fromUtf8("rbMatrix7"))
        self.verticalLayout.addWidget(self.rbMatrix7)
        self.rbMatrix8 = QtGui.QRadioButton(self.widget)
        self.rbMatrix8.setObjectName(_fromUtf8("rbMatrix8"))
        self.verticalLayout.addWidget(self.rbMatrix8)
        self.groupBoxShiftCore = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxShiftCore.setGeometry(QtCore.QRect(740, 250, 101, 231))
        self.groupBoxShiftCore.setObjectName(_fromUtf8("groupBoxShiftCore"))
        self.chkShiftCore = QtGui.QCheckBox(self.groupBoxShiftCore)
        self.chkShiftCore.setGeometry(QtCore.QRect(20, 200, 70, 17))
        self.chkShiftCore.setObjectName(_fromUtf8("chkShiftCore"))
        self.widget1 = QtGui.QWidget(self.groupBoxShiftCore)
        self.widget1.setGeometry(QtCore.QRect(10, 134, 81, 61))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.rbLeft = QtGui.QRadioButton(self.widget1)
        self.rbLeft.setObjectName(_fromUtf8("rbLeft"))
        self.verticalLayout_2.addWidget(self.rbLeft)
        self.rbRight = QtGui.QRadioButton(self.widget1)
        self.rbRight.setObjectName(_fromUtf8("rbRight"))
        self.verticalLayout_2.addWidget(self.rbRight)
        self.rbRandom = QtGui.QRadioButton(self.widget1)
        self.rbRandom.setObjectName(_fromUtf8("rbRandom"))
        self.verticalLayout_2.addWidget(self.rbRandom)
        self.widget2 = QtGui.QWidget(self.groupBoxShiftCore)
        self.widget2.setGeometry(QtCore.QRect(10, 20, 91, 111))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.gridLayout = QtGui.QGridLayout(self.widget2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.rbShift1 = QtGui.QRadioButton(self.widget2)
        self.rbShift1.setObjectName(_fromUtf8("rbShift1"))
        self.gridLayout.addWidget(self.rbShift1, 0, 0, 1, 1)
        self.rbShift8 = QtGui.QRadioButton(self.widget2)
        self.rbShift8.setObjectName(_fromUtf8("rbShift8"))
        self.gridLayout.addWidget(self.rbShift8, 0, 1, 1, 1)
        self.rbShift2 = QtGui.QRadioButton(self.widget2)
        self.rbShift2.setObjectName(_fromUtf8("rbShift2"))
        self.gridLayout.addWidget(self.rbShift2, 1, 0, 1, 1)
        self.rbShift13 = QtGui.QRadioButton(self.widget2)
        self.rbShift13.setObjectName(_fromUtf8("rbShift13"))
        self.gridLayout.addWidget(self.rbShift13, 1, 1, 1, 1)
        self.rbShiftR = QtGui.QRadioButton(self.widget2)
        self.rbShiftR.setObjectName(_fromUtf8("rbShiftR"))
        self.gridLayout.addWidget(self.rbShiftR, 2, 0, 1, 1)
        self.rbShift21 = QtGui.QRadioButton(self.widget2)
        self.rbShift21.setObjectName(_fromUtf8("rbShift21"))
        self.gridLayout.addWidget(self.rbShift21, 2, 1, 1, 1)
        self.rbShift3 = QtGui.QRadioButton(self.widget2)
        self.rbShift3.setObjectName(_fromUtf8("rbShift3"))
        self.gridLayout.addWidget(self.rbShift3, 3, 0, 1, 1)
        self.rbShift34 = QtGui.QRadioButton(self.widget2)
        self.rbShift34.setObjectName(_fromUtf8("rbShift34"))
        self.gridLayout.addWidget(self.rbShift34, 3, 1, 1, 1)
        self.rbShift5 = QtGui.QRadioButton(self.widget2)
        self.rbShift5.setObjectName(_fromUtf8("rbShift5"))
        self.gridLayout.addWidget(self.rbShift5, 4, 0, 1, 1)
        self.rbShift55 = QtGui.QRadioButton(self.widget2)
        self.rbShift55.setObjectName(_fromUtf8("rbShift55"))
        self.gridLayout.addWidget(self.rbShift55, 4, 1, 1, 1)
        self.groupBoxTranspose = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxTranspose.setGeometry(QtCore.QRect(840, 250, 151, 231))
        self.groupBoxTranspose.setObjectName(_fromUtf8("groupBoxTranspose"))
        self.chkTranspose1 = QtGui.QCheckBox(self.groupBoxTranspose)
        self.chkTranspose1.setGeometry(QtCore.QRect(11, 21, 29, 17))
        self.chkTranspose1.setObjectName(_fromUtf8("chkTranspose1"))
        self.chkTranspose2 = QtGui.QCheckBox(self.groupBoxTranspose)
        self.chkTranspose2.setGeometry(QtCore.QRect(11, 44, 29, 17))
        self.chkTranspose2.setObjectName(_fromUtf8("chkTranspose2"))
        self.chkTranspose3 = QtGui.QCheckBox(self.groupBoxTranspose)
        self.chkTranspose3.setGeometry(QtCore.QRect(11, 67, 29, 17))
        self.chkTranspose3.setObjectName(_fromUtf8("chkTranspose3"))
        self.chkTranspose4 = QtGui.QCheckBox(self.groupBoxTranspose)
        self.chkTranspose4.setGeometry(QtCore.QRect(11, 90, 29, 17))
        self.chkTranspose4.setObjectName(_fromUtf8("chkTranspose4"))
        self.chkTranspose5 = QtGui.QCheckBox(self.groupBoxTranspose)
        self.chkTranspose5.setGeometry(QtCore.QRect(11, 113, 29, 17))
        self.chkTranspose5.setObjectName(_fromUtf8("chkTranspose5"))
        self.chkTranspose6 = QtGui.QCheckBox(self.groupBoxTranspose)
        self.chkTranspose6.setGeometry(QtCore.QRect(11, 136, 29, 17))
        self.chkTranspose6.setObjectName(_fromUtf8("chkTranspose6"))
        self.chkTranspose7 = QtGui.QCheckBox(self.groupBoxTranspose)
        self.chkTranspose7.setGeometry(QtCore.QRect(11, 159, 29, 17))
        self.chkTranspose7.setObjectName(_fromUtf8("chkTranspose7"))
        self.chkTranspose8 = QtGui.QCheckBox(self.groupBoxTranspose)
        self.chkTranspose8.setGeometry(QtCore.QRect(11, 182, 29, 17))
        self.chkTranspose8.setObjectName(_fromUtf8("chkTranspose8"))
        self.chkTranspose = QtGui.QCheckBox(self.groupBoxTranspose)
        self.chkTranspose.setGeometry(QtCore.QRect(50, 210, 61, 20))
        self.chkTranspose.setObjectName(_fromUtf8("chkTranspose"))
        self.widget3 = QtGui.QWidget(self.groupBoxTranspose)
        self.widget3.setGeometry(QtCore.QRect(41, 21, 44, 181))
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.sbTransOct1 = QtGui.QSpinBox(self.widget3)
        self.sbTransOct1.setObjectName(_fromUtf8("sbTransOct1"))
        self.verticalLayout_3.addWidget(self.sbTransOct1)
        self.sbTransOct2 = QtGui.QSpinBox(self.widget3)
        self.sbTransOct2.setObjectName(_fromUtf8("sbTransOct2"))
        self.verticalLayout_3.addWidget(self.sbTransOct2)
        self.sbTransOct3 = QtGui.QSpinBox(self.widget3)
        self.sbTransOct3.setObjectName(_fromUtf8("sbTransOct3"))
        self.verticalLayout_3.addWidget(self.sbTransOct3)
        self.sbTransOct4 = QtGui.QSpinBox(self.widget3)
        self.sbTransOct4.setObjectName(_fromUtf8("sbTransOct4"))
        self.verticalLayout_3.addWidget(self.sbTransOct4)
        self.sbTransOct5 = QtGui.QSpinBox(self.widget3)
        self.sbTransOct5.setObjectName(_fromUtf8("sbTransOct5"))
        self.verticalLayout_3.addWidget(self.sbTransOct5)
        self.sbTransOct6 = QtGui.QSpinBox(self.widget3)
        self.sbTransOct6.setObjectName(_fromUtf8("sbTransOct6"))
        self.verticalLayout_3.addWidget(self.sbTransOct6)
        self.sbTransOct7 = QtGui.QSpinBox(self.widget3)
        self.sbTransOct7.setObjectName(_fromUtf8("sbTransOct7"))
        self.verticalLayout_3.addWidget(self.sbTransOct7)
        self.sbTransOct8 = QtGui.QSpinBox(self.widget3)
        self.sbTransOct8.setObjectName(_fromUtf8("sbTransOct8"))
        self.verticalLayout_3.addWidget(self.sbTransOct8)
        self.widget4 = QtGui.QWidget(self.groupBoxTranspose)
        self.widget4.setGeometry(QtCore.QRect(91, 21, 44, 181))
        self.widget4.setObjectName(_fromUtf8("widget4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.sbTransRep1 = QtGui.QSpinBox(self.widget4)
        self.sbTransRep1.setObjectName(_fromUtf8("sbTransRep1"))
        self.verticalLayout_5.addWidget(self.sbTransRep1)
        self.sbTransRep2 = QtGui.QSpinBox(self.widget4)
        self.sbTransRep2.setObjectName(_fromUtf8("sbTransRep2"))
        self.verticalLayout_5.addWidget(self.sbTransRep2)
        self.sbTransRep3 = QtGui.QSpinBox(self.widget4)
        self.sbTransRep3.setObjectName(_fromUtf8("sbTransRep3"))
        self.verticalLayout_5.addWidget(self.sbTransRep3)
        self.sbTransRep4 = QtGui.QSpinBox(self.widget4)
        self.sbTransRep4.setObjectName(_fromUtf8("sbTransRep4"))
        self.verticalLayout_5.addWidget(self.sbTransRep4)
        self.sbTransRep5 = QtGui.QSpinBox(self.widget4)
        self.sbTransRep5.setObjectName(_fromUtf8("sbTransRep5"))
        self.verticalLayout_5.addWidget(self.sbTransRep5)
        self.sbTransRep6 = QtGui.QSpinBox(self.widget4)
        self.sbTransRep6.setObjectName(_fromUtf8("sbTransRep6"))
        self.verticalLayout_5.addWidget(self.sbTransRep6)
        self.sbTransRep7 = QtGui.QSpinBox(self.widget4)
        self.sbTransRep7.setObjectName(_fromUtf8("sbTransRep7"))
        self.verticalLayout_5.addWidget(self.sbTransRep7)
        self.sbTransRep8 = QtGui.QSpinBox(self.widget4)
        self.sbTransRep8.setObjectName(_fromUtf8("sbTransRep8"))
        self.verticalLayout_5.addWidget(self.sbTransRep8)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 250, 81, 431))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget_2 = QtGui.QWidget(self.groupBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 20, 51, 180))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.radioButton = QtGui.QRadioButton(self.layoutWidget_2)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.verticalLayout_4.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.layoutWidget_2)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.verticalLayout_4.addWidget(self.radioButton_2)
        self.radioButton_3 = QtGui.QRadioButton(self.layoutWidget_2)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.verticalLayout_4.addWidget(self.radioButton_3)
        self.radioButton_4 = QtGui.QRadioButton(self.layoutWidget_2)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.verticalLayout_4.addWidget(self.radioButton_4)
        self.radioButton_5 = QtGui.QRadioButton(self.layoutWidget_2)
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.verticalLayout_4.addWidget(self.radioButton_5)
        self.radioButton_6 = QtGui.QRadioButton(self.layoutWidget_2)
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.verticalLayout_4.addWidget(self.radioButton_6)
        self.radioButton_7 = QtGui.QRadioButton(self.layoutWidget_2)
        self.radioButton_7.setObjectName(_fromUtf8("radioButton_7"))
        self.verticalLayout_4.addWidget(self.radioButton_7)
        self.radioButton_8 = QtGui.QRadioButton(self.layoutWidget_2)
        self.radioButton_8.setObjectName(_fromUtf8("radioButton_8"))
        self.verticalLayout_4.addWidget(self.radioButton_8)
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(10, 220, 61, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 240, 61, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 260, 61, 23))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 280, 61, 23))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 300, 61, 23))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_6 = QtGui.QPushButton(self.groupBox)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 320, 61, 23))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(102, 262, 559, 47))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_3.setGeometry(QtCore.QRect(11, 22, 29, 17))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.spinBox_3 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_3.setGeometry(QtCore.QRect(502, 21, 33, 20))
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.radioButton_25 = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_25.setGeometry(QtCore.QRect(66, 22, 30, 17))
        self.radioButton_25.setObjectName(_fromUtf8("radioButton_25"))
        self.radioButton_26 = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_26.setGeometry(QtCore.QRect(120, 22, 29, 17))
        self.radioButton_26.setObjectName(_fromUtf8("radioButton_26"))
        self.radioButton_27 = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_27.setGeometry(QtCore.QRect(175, 22, 30, 17))
        self.radioButton_27.setObjectName(_fromUtf8("radioButton_27"))
        self.radioButton_28 = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_28.setGeometry(QtCore.QRect(229, 22, 30, 17))
        self.radioButton_28.setObjectName(_fromUtf8("radioButton_28"))
        self.radioButton_29 = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_29.setGeometry(QtCore.QRect(284, 22, 29, 17))
        self.radioButton_29.setObjectName(_fromUtf8("radioButton_29"))
        self.radioButton_30 = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_30.setGeometry(QtCore.QRect(338, 22, 29, 17))
        self.radioButton_30.setObjectName(_fromUtf8("radioButton_30"))
        self.radioButton_31 = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_31.setGeometry(QtCore.QRect(393, 22, 30, 17))
        self.radioButton_31.setObjectName(_fromUtf8("radioButton_31"))
        self.radioButton_32 = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_32.setGeometry(QtCore.QRect(447, 22, 30, 17))
        self.radioButton_32.setObjectName(_fromUtf8("radioButton_32"))
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(102, 315, 559, 47))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.checkBox_4 = QtGui.QCheckBox(self.groupBox_6)
        self.checkBox_4.setGeometry(QtCore.QRect(12, 22, 29, 17))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.spinBox_4 = QtGui.QSpinBox(self.groupBox_6)
        self.spinBox_4.setGeometry(QtCore.QRect(503, 21, 33, 20))
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.radioButton_40 = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_40.setGeometry(QtCore.QRect(448, 22, 30, 17))
        self.radioButton_40.setObjectName(_fromUtf8("radioButton_40"))
        self.radioButton_33 = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_33.setGeometry(QtCore.QRect(67, 22, 30, 17))
        self.radioButton_33.setObjectName(_fromUtf8("radioButton_33"))
        self.radioButton_36 = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_36.setGeometry(QtCore.QRect(230, 22, 30, 17))
        self.radioButton_36.setObjectName(_fromUtf8("radioButton_36"))
        self.radioButton_35 = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_35.setGeometry(QtCore.QRect(176, 22, 30, 17))
        self.radioButton_35.setObjectName(_fromUtf8("radioButton_35"))
        self.radioButton_34 = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_34.setGeometry(QtCore.QRect(121, 22, 29, 17))
        self.radioButton_34.setObjectName(_fromUtf8("radioButton_34"))
        self.radioButton_37 = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_37.setGeometry(QtCore.QRect(285, 22, 29, 17))
        self.radioButton_37.setObjectName(_fromUtf8("radioButton_37"))
        self.radioButton_38 = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_38.setGeometry(QtCore.QRect(339, 22, 29, 17))
        self.radioButton_38.setObjectName(_fromUtf8("radioButton_38"))
        self.radioButton_39 = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_39.setGeometry(QtCore.QRect(394, 22, 30, 17))
        self.radioButton_39.setObjectName(_fromUtf8("radioButton_39"))
        self.checkBox_4.raise_()
        self.spinBox_4.raise_()
        self.groupBox_5.raise_()
        self.groupBox_7 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(102, 368, 559, 47))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.checkBox_5 = QtGui.QCheckBox(self.groupBox_7)
        self.checkBox_5.setGeometry(QtCore.QRect(11, 22, 29, 17))
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.spinBox_5 = QtGui.QSpinBox(self.groupBox_7)
        self.spinBox_5.setGeometry(QtCore.QRect(502, 21, 33, 20))
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.radioButton_41 = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_41.setGeometry(QtCore.QRect(66, 22, 30, 17))
        self.radioButton_41.setObjectName(_fromUtf8("radioButton_41"))
        self.radioButton_42 = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_42.setGeometry(QtCore.QRect(120, 22, 29, 17))
        self.radioButton_42.setObjectName(_fromUtf8("radioButton_42"))
        self.radioButton_43 = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_43.setGeometry(QtCore.QRect(175, 22, 30, 17))
        self.radioButton_43.setObjectName(_fromUtf8("radioButton_43"))
        self.radioButton_44 = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_44.setGeometry(QtCore.QRect(229, 22, 30, 17))
        self.radioButton_44.setObjectName(_fromUtf8("radioButton_44"))
        self.radioButton_45 = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_45.setGeometry(QtCore.QRect(284, 22, 29, 17))
        self.radioButton_45.setObjectName(_fromUtf8("radioButton_45"))
        self.radioButton_46 = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_46.setGeometry(QtCore.QRect(338, 22, 29, 17))
        self.radioButton_46.setObjectName(_fromUtf8("radioButton_46"))
        self.radioButton_47 = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_47.setGeometry(QtCore.QRect(393, 22, 30, 17))
        self.radioButton_47.setObjectName(_fromUtf8("radioButton_47"))
        self.radioButton_48 = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_48.setGeometry(QtCore.QRect(447, 22, 30, 17))
        self.radioButton_48.setObjectName(_fromUtf8("radioButton_48"))
        self.groupBox_9 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_9.setGeometry(QtCore.QRect(102, 421, 559, 48))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.checkBox_7 = QtGui.QCheckBox(self.groupBox_9)
        self.checkBox_7.setGeometry(QtCore.QRect(11, 22, 29, 17))
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.spinBox_7 = QtGui.QSpinBox(self.groupBox_9)
        self.spinBox_7.setGeometry(QtCore.QRect(502, 21, 33, 20))
        self.spinBox_7.setObjectName(_fromUtf8("spinBox_7"))
        self.radioButton_57 = QtGui.QRadioButton(self.groupBox_9)
        self.radioButton_57.setGeometry(QtCore.QRect(66, 22, 30, 17))
        self.radioButton_57.setObjectName(_fromUtf8("radioButton_57"))
        self.radioButton_58 = QtGui.QRadioButton(self.groupBox_9)
        self.radioButton_58.setGeometry(QtCore.QRect(120, 22, 29, 17))
        self.radioButton_58.setObjectName(_fromUtf8("radioButton_58"))
        self.radioButton_59 = QtGui.QRadioButton(self.groupBox_9)
        self.radioButton_59.setGeometry(QtCore.QRect(175, 22, 30, 17))
        self.radioButton_59.setObjectName(_fromUtf8("radioButton_59"))
        self.radioButton_60 = QtGui.QRadioButton(self.groupBox_9)
        self.radioButton_60.setGeometry(QtCore.QRect(229, 22, 30, 17))
        self.radioButton_60.setObjectName(_fromUtf8("radioButton_60"))
        self.radioButton_61 = QtGui.QRadioButton(self.groupBox_9)
        self.radioButton_61.setGeometry(QtCore.QRect(284, 22, 29, 17))
        self.radioButton_61.setObjectName(_fromUtf8("radioButton_61"))
        self.radioButton_62 = QtGui.QRadioButton(self.groupBox_9)
        self.radioButton_62.setGeometry(QtCore.QRect(338, 22, 29, 17))
        self.radioButton_62.setObjectName(_fromUtf8("radioButton_62"))
        self.radioButton_63 = QtGui.QRadioButton(self.groupBox_9)
        self.radioButton_63.setGeometry(QtCore.QRect(393, 22, 30, 17))
        self.radioButton_63.setObjectName(_fromUtf8("radioButton_63"))
        self.radioButton_64 = QtGui.QRadioButton(self.groupBox_9)
        self.radioButton_64.setGeometry(QtCore.QRect(447, 22, 30, 17))
        self.radioButton_64.setObjectName(_fromUtf8("radioButton_64"))
        self.checkBox_7.raise_()
        self.spinBox_7.raise_()
        self.dRepeat13 = QtGui.QDial(self.centralwidget)
        self.dRepeat13.setGeometry(QtCore.QRect(730, 140, 50, 64))
        self.dRepeat13.setMaximum(7)
        self.dRepeat13.setObjectName(_fromUtf8("dRepeat13"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(430, 0, 46, 13))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.cbNote16 = QtGui.QComboBox(self.centralwidget)
        self.cbNote16.setGeometry(QtCore.QRect(910, 70, 61, 22))
        self.cbNote16.setObjectName(_fromUtf8("cbNote16"))
        self.cbNote15 = QtGui.QComboBox(self.centralwidget)
        self.cbNote15.setGeometry(QtCore.QRect(850, 70, 61, 22))
        self.cbNote15.setObjectName(_fromUtf8("cbNote15"))
        self.dRepeat1 = QtGui.QDial(self.centralwidget)
        self.dRepeat1.setGeometry(QtCore.QRect(10, 140, 50, 64))
        self.dRepeat1.setStyleSheet(_fromUtf8("background-color: rgb(255,0,0);\n"
"color: rgb(0,255,0);"))
        self.dRepeat1.setMaximum(7)
        self.dRepeat1.setObjectName(_fromUtf8("dRepeat1"))
        self.dRepeat8 = QtGui.QDial(self.centralwidget)
        self.dRepeat8.setGeometry(QtCore.QRect(430, 140, 50, 64))
        self.dRepeat8.setMaximum(7)
        self.dRepeat8.setObjectName(_fromUtf8("dRepeat8"))
        self.dRepeat7 = QtGui.QDial(self.centralwidget)
        self.dRepeat7.setGeometry(QtCore.QRect(370, 140, 50, 64))
        self.dRepeat7.setMaximum(7)
        self.dRepeat7.setObjectName(_fromUtf8("dRepeat7"))
        self.cbNote8 = QtGui.QComboBox(self.centralwidget)
        self.cbNote8.setGeometry(QtCore.QRect(430, 70, 61, 22))
        self.cbNote8.setObjectName(_fromUtf8("cbNote8"))
        self.sbSeq = QtGui.QSpinBox(self.centralwidget)
        self.sbSeq.setGeometry(QtCore.QRect(370, 20, 42, 22))
        self.sbSeq.setObjectName(_fromUtf8("sbSeq"))
        self.dRepeat15 = QtGui.QDial(self.centralwidget)
        self.dRepeat15.setGeometry(QtCore.QRect(850, 140, 50, 64))
        self.dRepeat15.setMaximum(7)
        self.dRepeat15.setObjectName(_fromUtf8("dRepeat15"))
        self.cbNote7 = QtGui.QComboBox(self.centralwidget)
        self.cbNote7.setGeometry(QtCore.QRect(370, 70, 61, 22))
        self.cbNote7.setObjectName(_fromUtf8("cbNote7"))
        self.dRepeat11 = QtGui.QDial(self.centralwidget)
        self.dRepeat11.setGeometry(QtCore.QRect(610, 140, 50, 64))
        self.dRepeat11.setMaximum(7)
        self.dRepeat11.setObjectName(_fromUtf8("dRepeat11"))
        self.dRepeat5 = QtGui.QDial(self.centralwidget)
        self.dRepeat5.setGeometry(QtCore.QRect(250, 140, 50, 64))
        self.dRepeat5.setMaximum(7)
        self.dRepeat5.setObjectName(_fromUtf8("dRepeat5"))
        self.cbNote3 = QtGui.QComboBox(self.centralwidget)
        self.cbNote3.setGeometry(QtCore.QRect(130, 70, 61, 22))
        self.cbNote3.setObjectName(_fromUtf8("cbNote3"))
        self.cbNote13 = QtGui.QComboBox(self.centralwidget)
        self.cbNote13.setGeometry(QtCore.QRect(730, 70, 61, 22))
        self.cbNote13.setObjectName(_fromUtf8("cbNote13"))
        self.sbChannel = QtGui.QSpinBox(self.centralwidget)
        self.sbChannel.setGeometry(QtCore.QRect(190, 20, 42, 22))
        self.sbChannel.setObjectName(_fromUtf8("sbChannel"))
        self.cbMidiPort = QtGui.QComboBox(self.centralwidget)
        self.cbMidiPort.setGeometry(QtCore.QRect(20, 20, 161, 22))
        self.cbMidiPort.setObjectName(_fromUtf8("cbMidiPort"))
        self.cbNote1 = QtGui.QComboBox(self.centralwidget)
        self.cbNote1.setGeometry(QtCore.QRect(10, 70, 61, 22))
        self.cbNote1.setObjectName(_fromUtf8("cbNote1"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(370, 0, 61, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.cbNote10 = QtGui.QComboBox(self.centralwidget)
        self.cbNote10.setGeometry(QtCore.QRect(550, 70, 61, 22))
        self.cbNote10.setObjectName(_fromUtf8("cbNote10"))
        self.sbSteps = QtGui.QSpinBox(self.centralwidget)
        self.sbSteps.setGeometry(QtCore.QRect(540, 20, 42, 22))
        self.sbSteps.setObjectName(_fromUtf8("sbSteps"))
        self.cbNote11 = QtGui.QComboBox(self.centralwidget)
        self.cbNote11.setGeometry(QtCore.QRect(610, 70, 61, 22))
        self.cbNote11.setObjectName(_fromUtf8("cbNote11"))
        self.pbStart = QtGui.QPushButton(self.centralwidget)
        self.pbStart.setGeometry(QtCore.QRect(750, 10, 75, 23))
        self.pbStart.setObjectName(_fromUtf8("pbStart"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(480, 0, 46, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.cbNote9 = QtGui.QComboBox(self.centralwidget)
        self.cbNote9.setGeometry(QtCore.QRect(490, 70, 61, 22))
        self.cbNote9.setObjectName(_fromUtf8("cbNote9"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 0, 46, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.sbRow = QtGui.QSpinBox(self.centralwidget)
        self.sbRow.setGeometry(QtCore.QRect(480, 20, 42, 22))
        self.sbRow.setObjectName(_fromUtf8("sbRow"))
        self.layoutWidget_5 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 210, 951, 41))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.sbPPQ1 = QtGui.QSpinBox(self.layoutWidget_5)
        self.sbPPQ1.setObjectName(_fromUtf8("sbPPQ1"))
        self.horizontalLayout_4.addWidget(self.sbPPQ1)
        self.sbPPQ2 = QtGui.QSpinBox(self.layoutWidget_5)
        self.sbPPQ2.setObjectName(_fromUtf8("sbPPQ2"))
        self.horizontalLayout_4.addWidget(self.sbPPQ2)
        self.sbPPQ3 = QtGui.QSpinBox(self.layoutWidget_5)
        self.sbPPQ3.setObjectName(_fromUtf8("sbPPQ3"))
        self.horizontalLayout_4.addWidget(self.sbPPQ3)
        self.sbPPQ4 = QtGui.QSpinBox(self.layoutWidget_5)
        self.sbPPQ4.setObjectName(_fromUtf8("sbPPQ4"))
        self.horizontalLayout_4.addWidget(self.sbPPQ4)
        self.sbPPQ5 = QtGui.QSpinBox(self.layoutWidget_5)
        self.sbPPQ5.setObjectName(_fromUtf8("sbPPQ5"))
        self.horizontalLayout_4.addWidget(self.sbPPQ5)
        self.sbPPQ6 = QtGui.QSpinBox(self.layoutWidget_5)
        self.sbPPQ6.setObjectName(_fromUtf8("sbPPQ6"))
        self.horizontalLayout_4.addWidget(self.sbPPQ6)
        self.sbPPQ7 = QtGui.QSpinBox(self.layoutWidget_5)
        self.sbPPQ7.setObjectName(_fromUtf8("sbPPQ7"))
        self.horizontalLayout_4.addWidget(self.sbPPQ7)
        self.sbPPQ8 = QtGui.QSpinBox(self.layoutWidget_5)
        self.sbPPQ8.setObjectName(_fromUtf8("sbPPQ8"))
        self.horizontalLayout_4.addWidget(self.sbPPQ8)
        self.sbPPQ9 = QtGui.QSpinBox(self.layoutWidget_5)
        self.sbPPQ9.setObjectName(_fromUtf8("sbPPQ9"))
        self.horizontalLayout_4.addWidget(self.sbPPQ9)
        self.sbPPQ10 = QtGui.QSpinBox(self.layoutWidget_5)
        self.sbPPQ10.setObjectName(_fromUtf8("sbPPQ10"))
        self.horizontalLayout_4.addWidget(self.sbPPQ10)
        self.sbPPQ11 = QtGui.QSpinBox(self.layoutWidget_5)
        self.sbPPQ11.setObjectName(_fromUtf8("sbPPQ11"))
        self.horizontalLayout_4.addWidget(self.sbPPQ11)
        self.sbPPQ12 = QtGui.QSpinBox(self.layoutWidget_5)
        self.sbPPQ12.setObjectName(_fromUtf8("sbPPQ12"))
        self.horizontalLayout_4.addWidget(self.sbPPQ12)
        self.sbPPQ13 = QtGui.QSpinBox(self.layoutWidget_5)
        self.sbPPQ13.setObjectName(_fromUtf8("sbPPQ13"))
        self.horizontalLayout_4.addWidget(self.sbPPQ13)
        self.sbPPQ14 = QtGui.QSpinBox(self.layoutWidget_5)
        self.sbPPQ14.setObjectName(_fromUtf8("sbPPQ14"))
        self.horizontalLayout_4.addWidget(self.sbPPQ14)
        self.sbPPQ15 = QtGui.QSpinBox(self.layoutWidget_5)
        self.sbPPQ15.setObjectName(_fromUtf8("sbPPQ15"))
        self.horizontalLayout_4.addWidget(self.sbPPQ15)
        self.sbPPQ16 = QtGui.QSpinBox(self.layoutWidget_5)
        self.sbPPQ16.setObjectName(_fromUtf8("sbPPQ16"))
        self.horizontalLayout_4.addWidget(self.sbPPQ16)
        self.dRepeat10 = QtGui.QDial(self.centralwidget)
        self.dRepeat10.setGeometry(QtCore.QRect(550, 140, 50, 64))
        self.dRepeat10.setMaximum(7)
        self.dRepeat10.setObjectName(_fromUtf8("dRepeat10"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(540, 0, 46, 13))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.cbNote6 = QtGui.QComboBox(self.centralwidget)
        self.cbNote6.setGeometry(QtCore.QRect(310, 70, 61, 22))
        self.cbNote6.setObjectName(_fromUtf8("cbNote6"))
        self.cbNote4 = QtGui.QComboBox(self.centralwidget)
        self.cbNote4.setGeometry(QtCore.QRect(190, 70, 61, 22))
        self.cbNote4.setObjectName(_fromUtf8("cbNote4"))
        self.dRepeat6 = QtGui.QDial(self.centralwidget)
        self.dRepeat6.setGeometry(QtCore.QRect(310, 140, 50, 64))
        self.dRepeat6.setMaximum(7)
        self.dRepeat6.setObjectName(_fromUtf8("dRepeat6"))
        self.dRepeat9 = QtGui.QDial(self.centralwidget)
        self.dRepeat9.setGeometry(QtCore.QRect(490, 140, 50, 64))
        self.dRepeat9.setMaximum(7)
        self.dRepeat9.setObjectName(_fromUtf8("dRepeat9"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 0, 71, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.cbNote12 = QtGui.QComboBox(self.centralwidget)
        self.cbNote12.setGeometry(QtCore.QRect(670, 70, 61, 22))
        self.cbNote12.setObjectName(_fromUtf8("cbNote12"))
        self.cbNote14 = QtGui.QComboBox(self.centralwidget)
        self.cbNote14.setGeometry(QtCore.QRect(790, 70, 61, 22))
        self.cbNote14.setObjectName(_fromUtf8("cbNote14"))
        self.dRepeat16 = QtGui.QDial(self.centralwidget)
        self.dRepeat16.setGeometry(QtCore.QRect(910, 140, 50, 64))
        self.dRepeat16.setMaximum(7)
        self.dRepeat16.setObjectName(_fromUtf8("dRepeat16"))
        self.lcdNumber = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(840, 10, 101, 23))
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.dRepeat2 = QtGui.QDial(self.centralwidget)
        self.dRepeat2.setGeometry(QtCore.QRect(70, 140, 50, 64))
        self.dRepeat2.setStyleSheet(_fromUtf8("color: rgb(85, 170, 0);\n"
"background-color: rgb(99, 132, 46);"))
        self.dRepeat2.setMaximum(7)
        self.dRepeat2.setObjectName(_fromUtf8("dRepeat2"))
        self.dRepeat3 = QtGui.QDial(self.centralwidget)
        self.dRepeat3.setGeometry(QtCore.QRect(130, 140, 50, 64))
        self.dRepeat3.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 255);"))
        self.dRepeat3.setMaximum(7)
        self.dRepeat3.setObjectName(_fromUtf8("dRepeat3"))
        self.sbVoice = QtGui.QSpinBox(self.centralwidget)
        self.sbVoice.setGeometry(QtCore.QRect(430, 20, 42, 22))
        self.sbVoice.setObjectName(_fromUtf8("sbVoice"))
        self.dRepeat12 = QtGui.QDial(self.centralwidget)
        self.dRepeat12.setGeometry(QtCore.QRect(670, 140, 50, 64))
        self.dRepeat12.setMaximum(7)
        self.dRepeat12.setObjectName(_fromUtf8("dRepeat12"))
        self.layoutWidget_7 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_7.setGeometry(QtCore.QRect(10, 100, 961, 41))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.chkRest1 = QtGui.QCheckBox(self.layoutWidget_7)
        self.chkRest1.setObjectName(_fromUtf8("chkRest1"))
        self.horizontalLayout_6.addWidget(self.chkRest1)
        self.chkRest2 = QtGui.QCheckBox(self.layoutWidget_7)
        self.chkRest2.setObjectName(_fromUtf8("chkRest2"))
        self.horizontalLayout_6.addWidget(self.chkRest2)
        self.chkRest3 = QtGui.QCheckBox(self.layoutWidget_7)
        self.chkRest3.setObjectName(_fromUtf8("chkRest3"))
        self.horizontalLayout_6.addWidget(self.chkRest3)
        self.chkRest4 = QtGui.QCheckBox(self.layoutWidget_7)
        self.chkRest4.setObjectName(_fromUtf8("chkRest4"))
        self.horizontalLayout_6.addWidget(self.chkRest4)
        self.chkRest5 = QtGui.QCheckBox(self.layoutWidget_7)
        self.chkRest5.setObjectName(_fromUtf8("chkRest5"))
        self.horizontalLayout_6.addWidget(self.chkRest5)
        self.chkRest6 = QtGui.QCheckBox(self.layoutWidget_7)
        self.chkRest6.setObjectName(_fromUtf8("chkRest6"))
        self.horizontalLayout_6.addWidget(self.chkRest6)
        self.chkRest7 = QtGui.QCheckBox(self.layoutWidget_7)
        self.chkRest7.setObjectName(_fromUtf8("chkRest7"))
        self.horizontalLayout_6.addWidget(self.chkRest7)
        self.chkRest8 = QtGui.QCheckBox(self.layoutWidget_7)
        self.chkRest8.setObjectName(_fromUtf8("chkRest8"))
        self.horizontalLayout_6.addWidget(self.chkRest8)
        self.chkRest9 = QtGui.QCheckBox(self.layoutWidget_7)
        self.chkRest9.setObjectName(_fromUtf8("chkRest9"))
        self.horizontalLayout_6.addWidget(self.chkRest9)
        self.chkRest10 = QtGui.QCheckBox(self.layoutWidget_7)
        self.chkRest10.setObjectName(_fromUtf8("chkRest10"))
        self.horizontalLayout_6.addWidget(self.chkRest10)
        self.chkRest11 = QtGui.QCheckBox(self.layoutWidget_7)
        self.chkRest11.setObjectName(_fromUtf8("chkRest11"))
        self.horizontalLayout_6.addWidget(self.chkRest11)
        self.chkRest12 = QtGui.QCheckBox(self.layoutWidget_7)
        self.chkRest12.setObjectName(_fromUtf8("chkRest12"))
        self.horizontalLayout_6.addWidget(self.chkRest12)
        self.chkRest13 = QtGui.QCheckBox(self.layoutWidget_7)
        self.chkRest13.setObjectName(_fromUtf8("chkRest13"))
        self.horizontalLayout_6.addWidget(self.chkRest13)
        self.chkRest14 = QtGui.QCheckBox(self.layoutWidget_7)
        self.chkRest14.setObjectName(_fromUtf8("chkRest14"))
        self.horizontalLayout_6.addWidget(self.chkRest14)
        self.chkRest15 = QtGui.QCheckBox(self.layoutWidget_7)
        self.chkRest15.setObjectName(_fromUtf8("chkRest15"))
        self.horizontalLayout_6.addWidget(self.chkRest15)
        self.chkRest16 = QtGui.QCheckBox(self.layoutWidget_7)
        self.chkRest16.setObjectName(_fromUtf8("chkRest16"))
        self.horizontalLayout_6.addWidget(self.chkRest16)
        self.dRepeat14 = QtGui.QDial(self.centralwidget)
        self.dRepeat14.setGeometry(QtCore.QRect(790, 140, 50, 64))
        self.dRepeat14.setMaximum(7)
        self.dRepeat14.setObjectName(_fromUtf8("dRepeat14"))
        self.cbNote5 = QtGui.QComboBox(self.centralwidget)
        self.cbNote5.setGeometry(QtCore.QRect(250, 70, 61, 22))
        self.cbNote5.setObjectName(_fromUtf8("cbNote5"))
        self.dRepeat4 = QtGui.QDial(self.centralwidget)
        self.dRepeat4.setGeometry(QtCore.QRect(190, 140, 50, 64))
        self.dRepeat4.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.dRepeat4.setMaximum(7)
        self.dRepeat4.setObjectName(_fromUtf8("dRepeat4"))
        self.cbNote2 = QtGui.QComboBox(self.centralwidget)
        self.cbNote2.setGeometry(QtCore.QRect(70, 70, 61, 22))
        self.cbNote2.setObjectName(_fromUtf8("cbNote2"))
        self.spinBox_6 = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_6.setGeometry(QtCore.QRect(240, 20, 42, 22))
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.spinBox_8 = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_8.setGeometry(QtCore.QRect(290, 20, 42, 22))
        self.spinBox_8.setObjectName(_fromUtf8("spinBox_8"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(240, 0, 46, 13))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(290, 0, 46, 13))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.groupBox_15 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_15.setGeometry(QtCore.QRect(670, 480, 321, 201))
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.checkBox_13 = QtGui.QCheckBox(self.groupBox_15)
        self.checkBox_13.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.checkBox_13.setObjectName(_fromUtf8("checkBox_13"))
        self.checkBox_14 = QtGui.QCheckBox(self.groupBox_15)
        self.checkBox_14.setGeometry(QtCore.QRect(10, 40, 70, 17))
        self.checkBox_14.setObjectName(_fromUtf8("checkBox_14"))
        self.checkBox_15 = QtGui.QCheckBox(self.groupBox_15)
        self.checkBox_15.setGeometry(QtCore.QRect(10, 60, 70, 17))
        self.checkBox_15.setObjectName(_fromUtf8("checkBox_15"))
        self.checkBox_16 = QtGui.QCheckBox(self.groupBox_15)
        self.checkBox_16.setGeometry(QtCore.QRect(10, 80, 70, 17))
        self.checkBox_16.setObjectName(_fromUtf8("checkBox_16"))
        self.spinBox_15 = QtGui.QSpinBox(self.groupBox_15)
        self.spinBox_15.setGeometry(QtCore.QRect(90, 20, 42, 22))
        self.spinBox_15.setObjectName(_fromUtf8("spinBox_15"))
        self.spinBox_16 = QtGui.QSpinBox(self.groupBox_15)
        self.spinBox_16.setGeometry(QtCore.QRect(90, 40, 42, 22))
        self.spinBox_16.setObjectName(_fromUtf8("spinBox_16"))
        self.spinBox_17 = QtGui.QSpinBox(self.groupBox_15)
        self.spinBox_17.setGeometry(QtCore.QRect(90, 60, 42, 22))
        self.spinBox_17.setObjectName(_fromUtf8("spinBox_17"))
        self.spinBox_18 = QtGui.QSpinBox(self.groupBox_15)
        self.spinBox_18.setGeometry(QtCore.QRect(90, 80, 42, 22))
        self.spinBox_18.setObjectName(_fromUtf8("spinBox_18"))
        self.spinBox_19 = QtGui.QSpinBox(self.groupBox_15)
        self.spinBox_19.setGeometry(QtCore.QRect(140, 20, 42, 22))
        self.spinBox_19.setObjectName(_fromUtf8("spinBox_19"))
        self.spinBox_20 = QtGui.QSpinBox(self.groupBox_15)
        self.spinBox_20.setGeometry(QtCore.QRect(140, 40, 42, 22))
        self.spinBox_20.setObjectName(_fromUtf8("spinBox_20"))
        self.spinBox_21 = QtGui.QSpinBox(self.groupBox_15)
        self.spinBox_21.setGeometry(QtCore.QRect(140, 60, 42, 22))
        self.spinBox_21.setObjectName(_fromUtf8("spinBox_21"))
        self.spinBox_22 = QtGui.QSpinBox(self.groupBox_15)
        self.spinBox_22.setGeometry(QtCore.QRect(140, 80, 42, 22))
        self.spinBox_22.setObjectName(_fromUtf8("spinBox_22"))
        self.spinBox_23 = QtGui.QSpinBox(self.groupBox_15)
        self.spinBox_23.setGeometry(QtCore.QRect(140, 120, 42, 22))
        self.spinBox_23.setObjectName(_fromUtf8("spinBox_23"))
        self.spinBox_24 = QtGui.QSpinBox(self.groupBox_15)
        self.spinBox_24.setGeometry(QtCore.QRect(140, 140, 42, 22))
        self.spinBox_24.setObjectName(_fromUtf8("spinBox_24"))
        self.checkBox_17 = QtGui.QCheckBox(self.groupBox_15)
        self.checkBox_17.setGeometry(QtCore.QRect(10, 120, 70, 17))
        self.checkBox_17.setObjectName(_fromUtf8("checkBox_17"))
        self.spinBox_25 = QtGui.QSpinBox(self.groupBox_15)
        self.spinBox_25.setGeometry(QtCore.QRect(90, 160, 42, 22))
        self.spinBox_25.setObjectName(_fromUtf8("spinBox_25"))
        self.checkBox_18 = QtGui.QCheckBox(self.groupBox_15)
        self.checkBox_18.setGeometry(QtCore.QRect(10, 100, 70, 17))
        self.checkBox_18.setObjectName(_fromUtf8("checkBox_18"))
        self.spinBox_26 = QtGui.QSpinBox(self.groupBox_15)
        self.spinBox_26.setGeometry(QtCore.QRect(90, 120, 42, 22))
        self.spinBox_26.setObjectName(_fromUtf8("spinBox_26"))
        self.spinBox_27 = QtGui.QSpinBox(self.groupBox_15)
        self.spinBox_27.setGeometry(QtCore.QRect(90, 140, 42, 22))
        self.spinBox_27.setObjectName(_fromUtf8("spinBox_27"))
        self.checkBox_19 = QtGui.QCheckBox(self.groupBox_15)
        self.checkBox_19.setGeometry(QtCore.QRect(10, 140, 70, 17))
        self.checkBox_19.setObjectName(_fromUtf8("checkBox_19"))
        self.spinBox_28 = QtGui.QSpinBox(self.groupBox_15)
        self.spinBox_28.setGeometry(QtCore.QRect(90, 100, 42, 22))
        self.spinBox_28.setObjectName(_fromUtf8("spinBox_28"))
        self.spinBox_29 = QtGui.QSpinBox(self.groupBox_15)
        self.spinBox_29.setGeometry(QtCore.QRect(140, 100, 42, 22))
        self.spinBox_29.setObjectName(_fromUtf8("spinBox_29"))
        self.checkBox_20 = QtGui.QCheckBox(self.groupBox_15)
        self.checkBox_20.setGeometry(QtCore.QRect(10, 160, 70, 17))
        self.checkBox_20.setObjectName(_fromUtf8("checkBox_20"))
        self.spinBox_30 = QtGui.QSpinBox(self.groupBox_15)
        self.spinBox_30.setGeometry(QtCore.QRect(140, 160, 42, 22))
        self.spinBox_30.setObjectName(_fromUtf8("spinBox_30"))
        self.checkBox = QtGui.QCheckBox(self.groupBox_15)
        self.checkBox.setGeometry(QtCore.QRect(191, 22, 44, 17))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox_15)
        self.checkBox_2.setGeometry(QtCore.QRect(191, 42, 44, 17))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox_6 = QtGui.QCheckBox(self.groupBox_15)
        self.checkBox_6.setGeometry(QtCore.QRect(191, 62, 44, 17))
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.checkBox_9 = QtGui.QCheckBox(self.groupBox_15)
        self.checkBox_9.setGeometry(QtCore.QRect(191, 82, 44, 17))
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.checkBox_21 = QtGui.QCheckBox(self.groupBox_15)
        self.checkBox_21.setGeometry(QtCore.QRect(191, 102, 44, 17))
        self.checkBox_21.setObjectName(_fromUtf8("checkBox_21"))
        self.checkBox_24 = QtGui.QCheckBox(self.groupBox_15)
        self.checkBox_24.setGeometry(QtCore.QRect(191, 162, 44, 17))
        self.checkBox_24.setObjectName(_fromUtf8("checkBox_24"))
        self.checkBox_23 = QtGui.QCheckBox(self.groupBox_15)
        self.checkBox_23.setGeometry(QtCore.QRect(191, 142, 44, 17))
        self.checkBox_23.setObjectName(_fromUtf8("checkBox_23"))
        self.checkBox_22 = QtGui.QCheckBox(self.groupBox_15)
        self.checkBox_22.setGeometry(QtCore.QRect(191, 122, 44, 17))
        self.checkBox_22.setObjectName(_fromUtf8("checkBox_22"))
        self.widget5 = QtGui.QWidget(self.groupBox_15)
        self.widget5.setGeometry(QtCore.QRect(240, 20, 44, 161))
        self.widget5.setObjectName(_fromUtf8("widget5"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.widget5)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.spinBox = QtGui.QSpinBox(self.widget5)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.verticalLayout_8.addWidget(self.spinBox)
        self.spinBox_2 = QtGui.QSpinBox(self.widget5)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.verticalLayout_8.addWidget(self.spinBox_2)
        self.spinBox_9 = QtGui.QSpinBox(self.widget5)
        self.spinBox_9.setObjectName(_fromUtf8("spinBox_9"))
        self.verticalLayout_8.addWidget(self.spinBox_9)
        self.spinBox_11 = QtGui.QSpinBox(self.widget5)
        self.spinBox_11.setObjectName(_fromUtf8("spinBox_11"))
        self.verticalLayout_8.addWidget(self.spinBox_11)
        self.spinBox_31 = QtGui.QSpinBox(self.widget5)
        self.spinBox_31.setObjectName(_fromUtf8("spinBox_31"))
        self.verticalLayout_8.addWidget(self.spinBox_31)
        self.spinBox_32 = QtGui.QSpinBox(self.widget5)
        self.spinBox_32.setObjectName(_fromUtf8("spinBox_32"))
        self.verticalLayout_8.addWidget(self.spinBox_32)
        self.spinBox_33 = QtGui.QSpinBox(self.widget5)
        self.spinBox_33.setObjectName(_fromUtf8("spinBox_33"))
        self.verticalLayout_8.addWidget(self.spinBox_33)
        self.spinBox_34 = QtGui.QSpinBox(self.widget5)
        self.spinBox_34.setObjectName(_fromUtf8("spinBox_34"))
        self.verticalLayout_8.addWidget(self.spinBox_34)
        self.groupBox_14 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_14.setGeometry(QtCore.QRect(102, 630, 559, 51))
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.checkBox_12 = QtGui.QCheckBox(self.groupBox_14)
        self.checkBox_12.setGeometry(QtCore.QRect(11, 22, 29, 17))
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.spinBox_14 = QtGui.QSpinBox(self.groupBox_14)
        self.spinBox_14.setGeometry(QtCore.QRect(502, 21, 33, 20))
        self.spinBox_14.setObjectName(_fromUtf8("spinBox_14"))
        self.radioButton_97 = QtGui.QRadioButton(self.groupBox_14)
        self.radioButton_97.setGeometry(QtCore.QRect(66, 22, 30, 17))
        self.radioButton_97.setObjectName(_fromUtf8("radioButton_97"))
        self.radioButton_98 = QtGui.QRadioButton(self.groupBox_14)
        self.radioButton_98.setGeometry(QtCore.QRect(120, 22, 29, 17))
        self.radioButton_98.setObjectName(_fromUtf8("radioButton_98"))
        self.radioButton_99 = QtGui.QRadioButton(self.groupBox_14)
        self.radioButton_99.setGeometry(QtCore.QRect(175, 22, 30, 17))
        self.radioButton_99.setObjectName(_fromUtf8("radioButton_99"))
        self.radioButton_100 = QtGui.QRadioButton(self.groupBox_14)
        self.radioButton_100.setGeometry(QtCore.QRect(229, 22, 30, 17))
        self.radioButton_100.setObjectName(_fromUtf8("radioButton_100"))
        self.radioButton_101 = QtGui.QRadioButton(self.groupBox_14)
        self.radioButton_101.setGeometry(QtCore.QRect(284, 22, 29, 17))
        self.radioButton_101.setObjectName(_fromUtf8("radioButton_101"))
        self.radioButton_102 = QtGui.QRadioButton(self.groupBox_14)
        self.radioButton_102.setGeometry(QtCore.QRect(338, 22, 29, 17))
        self.radioButton_102.setObjectName(_fromUtf8("radioButton_102"))
        self.radioButton_103 = QtGui.QRadioButton(self.groupBox_14)
        self.radioButton_103.setGeometry(QtCore.QRect(393, 22, 30, 17))
        self.radioButton_103.setObjectName(_fromUtf8("radioButton_103"))
        self.radioButton_104 = QtGui.QRadioButton(self.groupBox_14)
        self.radioButton_104.setGeometry(QtCore.QRect(447, 22, 30, 17))
        self.radioButton_104.setObjectName(_fromUtf8("radioButton_104"))
        self.spinBox_14.raise_()
        self.checkBox_12.raise_()
        self.groupBox_13 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_13.setGeometry(QtCore.QRect(102, 581, 559, 47))
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.checkBox_11 = QtGui.QCheckBox(self.groupBox_13)
        self.checkBox_11.setGeometry(QtCore.QRect(11, 22, 29, 17))
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.spinBox_13 = QtGui.QSpinBox(self.groupBox_13)
        self.spinBox_13.setGeometry(QtCore.QRect(502, 21, 33, 20))
        self.spinBox_13.setObjectName(_fromUtf8("spinBox_13"))
        self.radioButton_89 = QtGui.QRadioButton(self.groupBox_13)
        self.radioButton_89.setGeometry(QtCore.QRect(66, 22, 30, 17))
        self.radioButton_89.setObjectName(_fromUtf8("radioButton_89"))
        self.radioButton_90 = QtGui.QRadioButton(self.groupBox_13)
        self.radioButton_90.setGeometry(QtCore.QRect(120, 22, 29, 17))
        self.radioButton_90.setObjectName(_fromUtf8("radioButton_90"))
        self.radioButton_91 = QtGui.QRadioButton(self.groupBox_13)
        self.radioButton_91.setGeometry(QtCore.QRect(175, 22, 30, 17))
        self.radioButton_91.setObjectName(_fromUtf8("radioButton_91"))
        self.radioButton_92 = QtGui.QRadioButton(self.groupBox_13)
        self.radioButton_92.setGeometry(QtCore.QRect(229, 22, 30, 17))
        self.radioButton_92.setObjectName(_fromUtf8("radioButton_92"))
        self.radioButton_93 = QtGui.QRadioButton(self.groupBox_13)
        self.radioButton_93.setGeometry(QtCore.QRect(284, 22, 29, 17))
        self.radioButton_93.setObjectName(_fromUtf8("radioButton_93"))
        self.radioButton_94 = QtGui.QRadioButton(self.groupBox_13)
        self.radioButton_94.setGeometry(QtCore.QRect(338, 22, 29, 17))
        self.radioButton_94.setObjectName(_fromUtf8("radioButton_94"))
        self.radioButton_95 = QtGui.QRadioButton(self.groupBox_13)
        self.radioButton_95.setGeometry(QtCore.QRect(393, 22, 30, 17))
        self.radioButton_95.setObjectName(_fromUtf8("radioButton_95"))
        self.radioButton_96 = QtGui.QRadioButton(self.groupBox_13)
        self.radioButton_96.setGeometry(QtCore.QRect(447, 22, 30, 17))
        self.radioButton_96.setObjectName(_fromUtf8("radioButton_96"))
        self.checkBox_11.raise_()
        self.spinBox_13.raise_()
        self.radioButton_93.raise_()
        self.groupBox_10 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_10.setGeometry(QtCore.QRect(102, 475, 559, 47))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.checkBox_8 = QtGui.QCheckBox(self.groupBox_10)
        self.checkBox_8.setGeometry(QtCore.QRect(11, 22, 29, 17))
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.spinBox_10 = QtGui.QSpinBox(self.groupBox_10)
        self.spinBox_10.setGeometry(QtCore.QRect(502, 21, 33, 20))
        self.spinBox_10.setObjectName(_fromUtf8("spinBox_10"))
        self.radioButton_73 = QtGui.QRadioButton(self.groupBox_10)
        self.radioButton_73.setGeometry(QtCore.QRect(66, 22, 30, 17))
        self.radioButton_73.setObjectName(_fromUtf8("radioButton_73"))
        self.radioButton_74 = QtGui.QRadioButton(self.groupBox_10)
        self.radioButton_74.setGeometry(QtCore.QRect(120, 22, 29, 17))
        self.radioButton_74.setObjectName(_fromUtf8("radioButton_74"))
        self.radioButton_76 = QtGui.QRadioButton(self.groupBox_10)
        self.radioButton_76.setGeometry(QtCore.QRect(229, 22, 30, 17))
        self.radioButton_76.setObjectName(_fromUtf8("radioButton_76"))
        self.radioButton_80 = QtGui.QRadioButton(self.groupBox_10)
        self.radioButton_80.setGeometry(QtCore.QRect(447, 22, 30, 17))
        self.radioButton_80.setObjectName(_fromUtf8("radioButton_80"))
        self.radioButton_78 = QtGui.QRadioButton(self.groupBox_10)
        self.radioButton_78.setGeometry(QtCore.QRect(338, 22, 29, 17))
        self.radioButton_78.setObjectName(_fromUtf8("radioButton_78"))
        self.radioButton_75 = QtGui.QRadioButton(self.groupBox_10)
        self.radioButton_75.setGeometry(QtCore.QRect(175, 22, 30, 17))
        self.radioButton_75.setObjectName(_fromUtf8("radioButton_75"))
        self.radioButton_79 = QtGui.QRadioButton(self.groupBox_10)
        self.radioButton_79.setGeometry(QtCore.QRect(393, 22, 30, 17))
        self.radioButton_79.setObjectName(_fromUtf8("radioButton_79"))
        self.radioButton_77 = QtGui.QRadioButton(self.groupBox_10)
        self.radioButton_77.setGeometry(QtCore.QRect(284, 22, 29, 17))
        self.radioButton_77.setObjectName(_fromUtf8("radioButton_77"))
        self.groupBox_12 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_12.setGeometry(QtCore.QRect(102, 528, 559, 47))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.checkBox_10 = QtGui.QCheckBox(self.groupBox_12)
        self.checkBox_10.setGeometry(QtCore.QRect(11, 22, 29, 17))
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.spinBox_12 = QtGui.QSpinBox(self.groupBox_12)
        self.spinBox_12.setGeometry(QtCore.QRect(502, 21, 33, 20))
        self.spinBox_12.setObjectName(_fromUtf8("spinBox_12"))
        self.radioButton_81 = QtGui.QRadioButton(self.groupBox_12)
        self.radioButton_81.setGeometry(QtCore.QRect(338, 22, 29, 17))
        self.radioButton_81.setObjectName(_fromUtf8("radioButton_81"))
        self.radioButton_82 = QtGui.QRadioButton(self.groupBox_12)
        self.radioButton_82.setGeometry(QtCore.QRect(66, 22, 30, 17))
        self.radioButton_82.setObjectName(_fromUtf8("radioButton_82"))
        self.radioButton_83 = QtGui.QRadioButton(self.groupBox_12)
        self.radioButton_83.setGeometry(QtCore.QRect(120, 22, 29, 17))
        self.radioButton_83.setObjectName(_fromUtf8("radioButton_83"))
        self.radioButton_84 = QtGui.QRadioButton(self.groupBox_12)
        self.radioButton_84.setGeometry(QtCore.QRect(393, 22, 30, 17))
        self.radioButton_84.setObjectName(_fromUtf8("radioButton_84"))
        self.radioButton_85 = QtGui.QRadioButton(self.groupBox_12)
        self.radioButton_85.setGeometry(QtCore.QRect(229, 22, 30, 17))
        self.radioButton_85.setObjectName(_fromUtf8("radioButton_85"))
        self.radioButton_86 = QtGui.QRadioButton(self.groupBox_12)
        self.radioButton_86.setGeometry(QtCore.QRect(447, 22, 30, 17))
        self.radioButton_86.setObjectName(_fromUtf8("radioButton_86"))
        self.radioButton_87 = QtGui.QRadioButton(self.groupBox_12)
        self.radioButton_87.setGeometry(QtCore.QRect(284, 22, 29, 17))
        self.radioButton_87.setObjectName(_fromUtf8("radioButton_87"))
        self.radioButton_88 = QtGui.QRadioButton(self.groupBox_12)
        self.radioButton_88.setGeometry(QtCore.QRect(175, 22, 30, 17))
        self.radioButton_88.setObjectName(_fromUtf8("radioButton_88"))
        self.widget6 = QtGui.QWidget(self.centralwidget)
        self.widget6.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.widget6.setObjectName(_fromUtf8("widget6"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget6)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.widget7 = QtGui.QWidget(self.centralwidget)
        self.widget7.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.widget7.setObjectName(_fromUtf8("widget7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.widget7)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1029, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBoxMatrix.setTitle(_translate("MainWindow", "Matrix", None))
        self.chkMatrix.setText(_translate("MainWindow", "On", None))
        self.rbMatrix1.setText(_translate("MainWindow", "1", None))
        self.rbMatrix2.setText(_translate("MainWindow", "2", None))
        self.rbMatrix3.setText(_translate("MainWindow", "3", None))
        self.rbMatrix4.setText(_translate("MainWindow", "4", None))
        self.rbMatrix5.setText(_translate("MainWindow", "5", None))
        self.rbMatrix6.setText(_translate("MainWindow", "6", None))
        self.rbMatrix7.setText(_translate("MainWindow", "7", None))
        self.rbMatrix8.setText(_translate("MainWindow", "8", None))
        self.groupBoxShiftCore.setTitle(_translate("MainWindow", "Shift Core", None))
        self.chkShiftCore.setText(_translate("MainWindow", "On/Off", None))
        self.rbLeft.setText(_translate("MainWindow", "Left", None))
        self.rbRight.setText(_translate("MainWindow", "Right", None))
        self.rbRandom.setText(_translate("MainWindow", "Random", None))
        self.rbShift1.setText(_translate("MainWindow", "1", None))
        self.rbShift8.setText(_translate("MainWindow", "8", None))
        self.rbShift2.setText(_translate("MainWindow", "2", None))
        self.rbShift13.setText(_translate("MainWindow", "13", None))
        self.rbShiftR.setText(_translate("MainWindow", "R", None))
        self.rbShift21.setText(_translate("MainWindow", "21", None))
        self.rbShift3.setText(_translate("MainWindow", "3", None))
        self.rbShift34.setText(_translate("MainWindow", "34", None))
        self.rbShift5.setText(_translate("MainWindow", "5", None))
        self.rbShift55.setText(_translate("MainWindow", "55", None))
        self.groupBoxTranspose.setTitle(_translate("MainWindow", "Transpose Matrix", None))
        self.chkTranspose1.setText(_translate("MainWindow", "1", None))
        self.chkTranspose2.setText(_translate("MainWindow", "2", None))
        self.chkTranspose3.setText(_translate("MainWindow", "3", None))
        self.chkTranspose4.setText(_translate("MainWindow", "4", None))
        self.chkTranspose5.setText(_translate("MainWindow", "5", None))
        self.chkTranspose6.setText(_translate("MainWindow", "6", None))
        self.chkTranspose7.setText(_translate("MainWindow", "7", None))
        self.chkTranspose8.setText(_translate("MainWindow", "8", None))
        self.chkTranspose.setText(_translate("MainWindow", "On/Off", None))
        self.groupBox.setTitle(_translate("MainWindow", "Pattern Variation", None))
        self.radioButton.setText(_translate("MainWindow", "A", None))
        self.radioButton_2.setText(_translate("MainWindow", "B", None))
        self.radioButton_3.setText(_translate("MainWindow", "C", None))
        self.radioButton_4.setText(_translate("MainWindow", "D", None))
        self.radioButton_5.setText(_translate("MainWindow", "E", None))
        self.radioButton_6.setText(_translate("MainWindow", "F", None))
        self.radioButton_7.setText(_translate("MainWindow", "G", None))
        self.radioButton_8.setText(_translate("MainWindow", "H", None))
        self.pushButton.setText(_translate("MainWindow", "Gen1", None))
        self.pushButton_2.setText(_translate("MainWindow", "Gen2", None))
        self.pushButton_3.setText(_translate("MainWindow", "Gen3", None))
        self.pushButton_4.setText(_translate("MainWindow", "Gen4", None))
        self.pushButton_5.setText(_translate("MainWindow", "Gen5", None))
        self.pushButton_6.setText(_translate("MainWindow", "Gen6", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Step Matrix 1", None))
        self.checkBox_3.setText(_translate("MainWindow", "1", None))
        self.radioButton_25.setText(_translate("MainWindow", "A", None))
        self.radioButton_26.setText(_translate("MainWindow", "B", None))
        self.radioButton_27.setText(_translate("MainWindow", "C", None))
        self.radioButton_28.setText(_translate("MainWindow", "D", None))
        self.radioButton_29.setText(_translate("MainWindow", "E", None))
        self.radioButton_30.setText(_translate("MainWindow", "F", None))
        self.radioButton_31.setText(_translate("MainWindow", "G", None))
        self.radioButton_32.setText(_translate("MainWindow", "H", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Step Matrix 2", None))
        self.checkBox_4.setText(_translate("MainWindow", "2", None))
        self.radioButton_40.setText(_translate("MainWindow", "H", None))
        self.radioButton_33.setText(_translate("MainWindow", "A", None))
        self.radioButton_36.setText(_translate("MainWindow", "D", None))
        self.radioButton_35.setText(_translate("MainWindow", "C", None))
        self.radioButton_34.setText(_translate("MainWindow", "B", None))
        self.radioButton_37.setText(_translate("MainWindow", "E", None))
        self.radioButton_38.setText(_translate("MainWindow", "F", None))
        self.radioButton_39.setText(_translate("MainWindow", "G", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Step Matrix 3", None))
        self.checkBox_5.setText(_translate("MainWindow", "3", None))
        self.radioButton_41.setText(_translate("MainWindow", "A", None))
        self.radioButton_42.setText(_translate("MainWindow", "B", None))
        self.radioButton_43.setText(_translate("MainWindow", "C", None))
        self.radioButton_44.setText(_translate("MainWindow", "D", None))
        self.radioButton_45.setText(_translate("MainWindow", "E", None))
        self.radioButton_46.setText(_translate("MainWindow", "F", None))
        self.radioButton_47.setText(_translate("MainWindow", "G", None))
        self.radioButton_48.setText(_translate("MainWindow", "H", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Step Matrix 4", None))
        self.checkBox_7.setText(_translate("MainWindow", "4", None))
        self.radioButton_57.setText(_translate("MainWindow", "A", None))
        self.radioButton_58.setText(_translate("MainWindow", "B", None))
        self.radioButton_59.setText(_translate("MainWindow", "C", None))
        self.radioButton_60.setText(_translate("MainWindow", "D", None))
        self.radioButton_61.setText(_translate("MainWindow", "E", None))
        self.radioButton_62.setText(_translate("MainWindow", "F", None))
        self.radioButton_63.setText(_translate("MainWindow", "G", None))
        self.radioButton_64.setText(_translate("MainWindow", "H", None))
        self.label_6.setText(_translate("MainWindow", "Voice", None))
        self.label_3.setText(_translate("MainWindow", "Sequencer", None))
        self.pbStart.setText(_translate("MainWindow", "Start", None))
        self.label_4.setText(_translate("MainWindow", "Row x16", None))
        self.label_2.setText(_translate("MainWindow", "Channel", None))
        self.label_5.setText(_translate("MainWindow", "Steps", None))
        self.label.setText(_translate("MainWindow", "MIDI Port", None))
        self.chkRest1.setText(_translate("MainWindow", "Rest", None))
        self.chkRest2.setText(_translate("MainWindow", "Rest", None))
        self.chkRest3.setText(_translate("MainWindow", "Rest", None))
        self.chkRest4.setText(_translate("MainWindow", "Rest", None))
        self.chkRest5.setText(_translate("MainWindow", "Rest", None))
        self.chkRest6.setText(_translate("MainWindow", "Rest", None))
        self.chkRest7.setText(_translate("MainWindow", "Rest", None))
        self.chkRest8.setText(_translate("MainWindow", "Rest", None))
        self.chkRest9.setText(_translate("MainWindow", "Rest", None))
        self.chkRest10.setText(_translate("MainWindow", "Rest", None))
        self.chkRest11.setText(_translate("MainWindow", "Rest", None))
        self.chkRest12.setText(_translate("MainWindow", "Rest", None))
        self.chkRest13.setText(_translate("MainWindow", "Rest", None))
        self.chkRest14.setText(_translate("MainWindow", "Rest", None))
        self.chkRest15.setText(_translate("MainWindow", "Rest", None))
        self.chkRest16.setText(_translate("MainWindow", "Rest", None))
        self.label_7.setText(_translate("MainWindow", "Banks", None))
        self.label_8.setText(_translate("MainWindow", "TextLabel", None))
        self.groupBox_15.setTitle(_translate("MainWindow", "GroupBox", None))
        self.checkBox_13.setText(_translate("MainWindow", "Program 1", None))
        self.checkBox_14.setText(_translate("MainWindow", "Program 2", None))
        self.checkBox_15.setText(_translate("MainWindow", "Program 3", None))
        self.checkBox_16.setText(_translate("MainWindow", "Program 4", None))
        self.checkBox_17.setText(_translate("MainWindow", "Program 2", None))
        self.checkBox_18.setText(_translate("MainWindow", "Program 1", None))
        self.checkBox_19.setText(_translate("MainWindow", "Program 3", None))
        self.checkBox_20.setText(_translate("MainWindow", "Program 4", None))
        self.checkBox.setText(_translate("MainWindow", "Var1", None))
        self.checkBox_2.setText(_translate("MainWindow", "Var1", None))
        self.checkBox_6.setText(_translate("MainWindow", "Var1", None))
        self.checkBox_9.setText(_translate("MainWindow", "Var1", None))
        self.checkBox_21.setText(_translate("MainWindow", "Var1", None))
        self.checkBox_24.setText(_translate("MainWindow", "Var1", None))
        self.checkBox_23.setText(_translate("MainWindow", "Var1", None))
        self.checkBox_22.setText(_translate("MainWindow", "Var1", None))
        self.groupBox_14.setTitle(_translate("MainWindow", "Step Matrix 8", None))
        self.checkBox_12.setText(_translate("MainWindow", "8", None))
        self.radioButton_97.setText(_translate("MainWindow", "A", None))
        self.radioButton_98.setText(_translate("MainWindow", "B", None))
        self.radioButton_99.setText(_translate("MainWindow", "C", None))
        self.radioButton_100.setText(_translate("MainWindow", "D", None))
        self.radioButton_101.setText(_translate("MainWindow", "E", None))
        self.radioButton_102.setText(_translate("MainWindow", "F", None))
        self.radioButton_103.setText(_translate("MainWindow", "G", None))
        self.radioButton_104.setText(_translate("MainWindow", "H", None))
        self.groupBox_13.setTitle(_translate("MainWindow", "Step Matrix 7", None))
        self.checkBox_11.setText(_translate("MainWindow", "7", None))
        self.radioButton_89.setText(_translate("MainWindow", "A", None))
        self.radioButton_90.setText(_translate("MainWindow", "B", None))
        self.radioButton_91.setText(_translate("MainWindow", "C", None))
        self.radioButton_92.setText(_translate("MainWindow", "D", None))
        self.radioButton_93.setText(_translate("MainWindow", "E", None))
        self.radioButton_94.setText(_translate("MainWindow", "F", None))
        self.radioButton_95.setText(_translate("MainWindow", "G", None))
        self.radioButton_96.setText(_translate("MainWindow", "H", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Step Matrix 5", None))
        self.checkBox_8.setText(_translate("MainWindow", "5", None))
        self.radioButton_73.setText(_translate("MainWindow", "A", None))
        self.radioButton_74.setText(_translate("MainWindow", "B", None))
        self.radioButton_76.setText(_translate("MainWindow", "D", None))
        self.radioButton_80.setText(_translate("MainWindow", "H", None))
        self.radioButton_78.setText(_translate("MainWindow", "F", None))
        self.radioButton_75.setText(_translate("MainWindow", "C", None))
        self.radioButton_79.setText(_translate("MainWindow", "G", None))
        self.radioButton_77.setText(_translate("MainWindow", "E", None))
        self.groupBox_12.setTitle(_translate("MainWindow", "Step Matrix 6", None))
        self.checkBox_10.setText(_translate("MainWindow", "6", None))
        self.radioButton_81.setText(_translate("MainWindow", "F", None))
        self.radioButton_82.setText(_translate("MainWindow", "A", None))
        self.radioButton_83.setText(_translate("MainWindow", "B", None))
        self.radioButton_84.setText(_translate("MainWindow", "G", None))
        self.radioButton_85.setText(_translate("MainWindow", "D", None))
        self.radioButton_86.setText(_translate("MainWindow", "H", None))
        self.radioButton_87.setText(_translate("MainWindow", "E", None))
        self.radioButton_88.setText(_translate("MainWindow", "C", None))

def run(app):
	sys.exit(app.exec_())
	MIDI_Shutdown()
	
	
if __name__ == '__main__':
	
	app = QtGui.QApplication(sys.argv)  # A new instance of QApplication
	app.setStyleSheet("""
		QMenuBar {
			background-color: rgb(93,93,93);
		}

		QMenuBar::item {
			background: rgb(93,93,93);
		}
		""")
	window = QtGui.QMainWindow()
	
	ui = Ui_MainWindow()
	ui.setupUi(window)
	window.show()
	run(app)